import type {
  AdminLevelConfig,
  EventTemplate,
  DifficultyCurve,
  TextResource,
  ConfigVersion,
  DashboardStats,
} from '../types/admin'

const now = Date.now()

export const mockLevels: AdminLevelConfig[] = [
  {
    id: 'level_001',
    name: 'classic_lv1',
    displayName: '初心·入门',
    description: '适合新手玩家的入门关卡，学习基础操作',
    gameMode: 'classic',
    duration: 120,
    status: 'published',
    tags: ['新手', '入门', '经典'],
    author: 'admin',
    versionId: 'v1.0.0',
    gears: [
      { id: 1, x: 200, y: 200, size: 'large', connectedTo: [2, 3], initialAngle: 0 },
      { id: 2, x: 100, y: 300, size: 'medium', connectedTo: [1], initialAngle: 45 },
      { id: 3, x: 300, y: 300, size: 'medium', connectedTo: [1, 4], initialAngle: 90 },
      { id: 4, x: 400, y: 200, size: 'small', connectedTo: [3], initialAngle: 0 },
    ],
    initialClockTime: { hours: 12, minutes: 0 },
    targetClockTime: { hours: 3, minutes: 0 },
    toleranceMinutes: 3,
    scoreMultiplier: 1,
    faultEvents: [],
    soundConfigs: [],
    createdAt: now - 86400000 * 10,
    updatedAt: now - 86400000 * 2,
  },
  {
    id: 'level_002',
    name: 'classic_lv2',
    displayName: '齿轮·进阶',
    description: '加入故障事件，考验应急处理能力',
    gameMode: 'classic',
    duration: 180,
    status: 'published',
    tags: ['进阶', '故障'],
    author: 'admin',
    versionId: 'v1.0.0',
    gears: [
      { id: 1, x: 300, y: 150, size: 'large', connectedTo: [2, 3, 4], initialAngle: 0 },
      { id: 2, x: 150, y: 250, size: 'medium', connectedTo: [1, 5], initialAngle: 30 },
      { id: 3, x: 300, y: 300, size: 'small', connectedTo: [1], initialAngle: 60 },
      { id: 4, x: 450, y: 250, size: 'medium', connectedTo: [1, 6], initialAngle: 90 },
      { id: 5, x: 100, y: 350, size: 'small', connectedTo: [2], initialAngle: 0 },
      { id: 6, x: 500, y: 350, size: 'small', connectedTo: [4], initialAngle: 120 },
    ],
    initialClockTime: { hours: 12, minutes: 0 },
    targetClockTime: { hours: 6, minutes: 30 },
    toleranceMinutes: 2,
    scoreMultiplier: 1.5,
    faultEvents: [
      { id: 'fe_001', name: 'early_jam', displayName: '早期卡顿', type: 'jam', triggerType: 'time', triggerValue: 30, targetGearIds: [2, 4], duration: 8, enabled: true },
      { id: 'fe_002', name: 'mid_slip', displayName: '中期打滑', type: 'slip', triggerType: 'rotations', triggerValue: 20, targetGearIds: [1], duration: 6, enabled: true },
    ],
    soundConfigs: [],
    createdAt: now - 86400000 * 7,
    updatedAt: now - 86400000 * 1,
  },
  {
    id: 'level_003',
    name: 'patrol_lv1',
    displayName: '夜巡·暮色',
    description: '夜巡模式第一关，包含多个时段',
    gameMode: 'patrol',
    duration: 240,
    status: 'testing',
    tags: ['夜巡', '多时段'],
    author: 'designer01',
    versionId: 'v1.1.0-beta',
    gears: [
      { id: 1, x: 300, y: 200, size: 'large', connectedTo: [2, 3], initialAngle: 0 },
      { id: 2, x: 150, y: 300, size: 'medium', connectedTo: [1], initialAngle: 0 },
      { id: 3, x: 450, y: 300, size: 'medium', connectedTo: [1], initialAngle: 0 },
    ],
    initialClockTime: { hours: 18, minutes: 0 },
    targetClockTime: { hours: 6, minutes: 0 },
    toleranceMinutes: 2,
    scoreMultiplier: 2,
    patrolPeriods: [
      { id: 'dusk', name: 'dusk', displayName: '黄昏', clockTime: '18:00', duration: 60, weather: { rain: 'calm', wind: 'light', lightning: 'calm' }, possibleFaults: ['jam', 'slip'], faultCount: 1, scoreMultiplier: 1, targetOffset: 5 },
      { id: 'earlyNight', name: 'earlyNight', displayName: '初夜', clockTime: '21:00', duration: 60, weather: { rain: 'light', wind: 'moderate', lightning: 'calm' }, possibleFaults: ['jam', 'slip', 'reverse'], faultCount: 2, scoreMultiplier: 1.5, targetOffset: 8 },
      { id: 'deepNight', name: 'deepNight', displayName: '深夜', clockTime: '00:00', duration: 60, weather: { rain: 'heavy', wind: 'heavy', lightning: 'moderate' }, possibleFaults: ['jam', 'slip', 'reverse', 'freeze'], faultCount: 3, scoreMultiplier: 2, targetOffset: 12 },
      { id: 'dawn', name: 'dawn', displayName: '黎明', clockTime: '04:00', duration: 60, weather: { rain: 'light', wind: 'light', lightning: 'calm' }, possibleFaults: ['jam', 'slip'], faultCount: 1, scoreMultiplier: 1.2, targetOffset: 6 },
    ],
    faultEvents: [],
    soundConfigs: [],
    createdAt: now - 86400000 * 3,
    updatedAt: now - 86400000 * 0.5,
  },
  {
    id: 'level_004',
    name: 'storm_lv1',
    displayName: '风暴·考验',
    description: '包含闪电风暴机制的高难度关卡',
    gameMode: 'classic',
    duration: 150,
    status: 'draft',
    tags: ['风暴', '高难度'],
    author: 'designer02',
    versionId: 'v1.1.0-beta',
    gears: [
      { id: 1, x: 300, y: 180, size: 'large', connectedTo: [2, 3, 4], initialAngle: 0 },
      { id: 2, x: 120, y: 280, size: 'medium', connectedTo: [1, 5], initialAngle: 45 },
      { id: 3, x: 300, y: 340, size: 'small', connectedTo: [1], initialAngle: 90 },
      { id: 4, x: 480, y: 280, size: 'medium', connectedTo: [1, 6], initialAngle: 135 },
      { id: 5, x: 60, y: 380, size: 'small', connectedTo: [2], initialAngle: 180 },
      { id: 6, x: 540, y: 380, size: 'small', connectedTo: [4], initialAngle: 225 },
    ],
    initialClockTime: { hours: 9, minutes: 0 },
    targetClockTime: { hours: 12, minutes: 0 },
    toleranceMinutes: 1,
    scoreMultiplier: 2.5,
    faultEvents: [
      { id: 'fe_003', name: 'random_freezes', displayName: '随机冻结', type: 'freeze', triggerType: 'random', triggerValue: 15, targetGearIds: [2, 3, 4], duration: 5, enabled: true },
    ],
    soundConfigs: [],
    createdAt: now - 86400000 * 1,
    updatedAt: now - 3600000 * 2,
  },
]

export const mockEventTemplates: EventTemplate[] = [
  {
    id: 'evt_tpl_001',
    name: 'early_stage_jam',
    displayName: '早期齿轮卡顿',
    description: '关卡开始后30秒左右触发齿轮卡顿，考验玩家应急能力',
    category: 'fault',
    weight: 3,
    enabled: true,
    author: 'admin',
    tags: ['早期', '卡顿'],
    events: [
      { id: 'fe_tpl_001', name: 'jam_30s', displayName: '30秒卡顿', type: 'jam', triggerType: 'time', triggerValue: 30, targetGearIds: [1, 2], duration: 8, enabled: true },
    ],
    conditions: [
      { type: 'time_range', min: 0, max: 60 },
      { type: 'level_progress', min: 0, max: 0.3 },
    ],
    createdAt: now - 86400000 * 14,
    updatedAt: now - 86400000 * 5,
  },
  {
    id: 'evt_tpl_002',
    name: 'mid_stage_complex',
    displayName: '中期复杂故障组合',
    description: '关卡中期触发多种故障组合，包括打滑和反向转动',
    category: 'fault',
    weight: 5,
    enabled: true,
    author: 'designer01',
    tags: ['中期', '组合'],
    events: [
      { id: 'fe_tpl_002', name: 'slip_mid', displayName: '中期打滑', type: 'slip', triggerType: 'rotations', triggerValue: 30, targetGearIds: [1], duration: 6, enabled: true },
      { id: 'fe_tpl_003', name: 'reverse_mid', displayName: '中期反向', type: 'reverse', triggerType: 'deviation', triggerValue: 5, targetGearIds: [2, 3], duration: 10, enabled: true },
    ],
    conditions: [
      { type: 'time_range', min: 60, max: 180 },
      { type: 'level_progress', min: 0.3, max: 0.7 },
    ],
    createdAt: now - 86400000 * 10,
    updatedAt: now - 86400000 * 3,
  },
  {
    id: 'evt_tpl_003',
    name: 'storm_lightning',
    displayName: '风暴闪电事件',
    description: '雷暴天气下的闪电攻击，会打乱齿轮角度',
    category: 'weather',
    weight: 4,
    enabled: true,
    author: 'designer02',
    tags: ['风暴', '闪电'],
    events: [],
    conditions: [
      { type: 'time_range', min: 60, max: 300 },
    ],
    createdAt: now - 86400000 * 6,
    updatedAt: now - 86400000 * 1,
  },
  {
    id: 'evt_tpl_004',
    name: 'reward_time_bonus',
    displayName: '时间奖励事件',
    description: '在低偏差状态下触发时间奖励',
    category: 'reward',
    weight: 2,
    enabled: false,
    author: 'admin',
    tags: ['奖励', '正向'],
    events: [],
    conditions: [
      { type: 'deviation_range', min: 0, max: 1 },
    ],
    createdAt: now - 86400000 * 4,
    updatedAt: now - 86400000 * 2,
  },
  {
    id: 'evt_tpl_005',
    name: 'late_stage_pressure',
    displayName: '末期高压组合',
    description: '关卡最后阶段的高强度故障组合，给玩家最大挑战',
    category: 'fault',
    weight: 6,
    enabled: true,
    author: 'admin',
    tags: ['末期', '高压'],
    events: [
      { id: 'fe_tpl_004', name: 'freeze_late', displayName: '末期冻结', type: 'freeze', triggerType: 'time', triggerValue: 150, targetGearIds: [1, 2, 3], duration: 7, enabled: true },
      { id: 'fe_tpl_005', name: 'jam_cascade', displayName: '级联卡顿', type: 'jam', triggerType: 'rotations', triggerValue: 60, targetGearIds: [4, 5, 6], duration: 5, enabled: true },
    ],
    conditions: [
      { type: 'time_range', min: 150, max: 999 },
      { type: 'level_progress', min: 0.7, max: 1 },
    ],
    createdAt: now - 86400000 * 5,
    updatedAt: now - 86400000 * 1,
  },
]

export const mockDifficultyCurves: DifficultyCurve[] = [
  {
    id: 'diff_easy',
    name: 'easy_curve',
    displayName: '轻松曲线',
    description: '适合新手玩家，难度平缓增长',
    level: 'easy',
    enabled: true,
    author: 'admin',
    points: [
      { levelProgress: 0, faultRate: 0.05, faultSeverity: 0.2, weatherIntensity: 0.1, targetOffset: 3, timePressure: 0.3, scoreMultiplier: 0.8 },
      { levelProgress: 0.25, faultRate: 0.1, faultSeverity: 0.3, weatherIntensity: 0.2, targetOffset: 4, timePressure: 0.4, scoreMultiplier: 0.9 },
      { levelProgress: 0.5, faultRate: 0.15, faultSeverity: 0.4, weatherIntensity: 0.3, targetOffset: 5, timePressure: 0.5, scoreMultiplier: 1.0 },
      { levelProgress: 0.75, faultRate: 0.2, faultSeverity: 0.5, weatherIntensity: 0.4, targetOffset: 6, timePressure: 0.6, scoreMultiplier: 1.1 },
      { levelProgress: 1, faultRate: 0.25, faultSeverity: 0.6, weatherIntensity: 0.5, targetOffset: 7, timePressure: 0.7, scoreMultiplier: 1.2 },
    ],
    createdAt: now - 86400000 * 20,
    updatedAt: now - 86400000 * 10,
  },
  {
    id: 'diff_normal',
    name: 'normal_curve',
    displayName: '标准曲线',
    description: '标准难度曲线，适合大多数玩家',
    level: 'normal',
    enabled: true,
    author: 'admin',
    points: [
      { levelProgress: 0, faultRate: 0.1, faultSeverity: 0.3, weatherIntensity: 0.2, targetOffset: 5, timePressure: 0.5, scoreMultiplier: 1.0 },
      { levelProgress: 0.25, faultRate: 0.2, faultSeverity: 0.45, weatherIntensity: 0.4, targetOffset: 7, timePressure: 0.6, scoreMultiplier: 1.1 },
      { levelProgress: 0.5, faultRate: 0.35, faultSeverity: 0.6, weatherIntensity: 0.6, targetOffset: 10, timePressure: 0.75, scoreMultiplier: 1.3 },
      { levelProgress: 0.75, faultRate: 0.5, faultSeverity: 0.75, weatherIntensity: 0.8, targetOffset: 13, timePressure: 0.85, scoreMultiplier: 1.6 },
      { levelProgress: 1, faultRate: 0.6, faultSeverity: 0.9, weatherIntensity: 1.0, targetOffset: 15, timePressure: 1.0, scoreMultiplier: 2.0 },
    ],
    createdAt: now - 86400000 * 20,
    updatedAt: now - 86400000 * 8,
  },
  {
    id: 'diff_hard',
    name: 'hard_curve',
    displayName: '挑战曲线',
    description: '高难度曲线，适合有经验的玩家',
    level: 'hard',
    enabled: true,
    author: 'designer01',
    points: [
      { levelProgress: 0, faultRate: 0.2, faultSeverity: 0.5, weatherIntensity: 0.4, targetOffset: 8, timePressure: 0.7, scoreMultiplier: 1.5 },
      { levelProgress: 0.25, faultRate: 0.35, faultSeverity: 0.65, weatherIntensity: 0.6, targetOffset: 10, timePressure: 0.8, scoreMultiplier: 1.8 },
      { levelProgress: 0.5, faultRate: 0.5, faultSeverity: 0.8, weatherIntensity: 0.8, targetOffset: 13, timePressure: 0.9, scoreMultiplier: 2.2 },
      { levelProgress: 0.75, faultRate: 0.7, faultSeverity: 0.9, weatherIntensity: 0.95, targetOffset: 16, timePressure: 0.95, scoreMultiplier: 2.8 },
      { levelProgress: 1, faultRate: 0.85, faultSeverity: 1.0, weatherIntensity: 1.0, targetOffset: 20, timePressure: 1.0, scoreMultiplier: 3.5 },
    ],
    createdAt: now - 86400000 * 15,
    updatedAt: now - 86400000 * 5,
  },
  {
    id: 'diff_expert',
    name: 'expert_curve',
    displayName: '大师曲线',
    description: '极致难度，只有顶尖玩家才能通过',
    level: 'expert',
    enabled: false,
    author: 'designer02',
    points: [
      { levelProgress: 0, faultRate: 0.4, faultSeverity: 0.7, weatherIntensity: 0.6, targetOffset: 12, timePressure: 0.9, scoreMultiplier: 2.5 },
      { levelProgress: 0.25, faultRate: 0.6, faultSeverity: 0.85, weatherIntensity: 0.85, targetOffset: 15, timePressure: 0.95, scoreMultiplier: 3.2 },
      { levelProgress: 0.5, faultRate: 0.75, faultSeverity: 0.95, weatherIntensity: 1.0, targetOffset: 18, timePressure: 1.0, scoreMultiplier: 4.0 },
      { levelProgress: 0.75, faultRate: 0.9, faultSeverity: 1.0, weatherIntensity: 1.0, targetOffset: 22, timePressure: 1.0, scoreMultiplier: 5.0 },
      { levelProgress: 1, faultRate: 1.0, faultSeverity: 1.0, weatherIntensity: 1.0, targetOffset: 25, timePressure: 1.0, scoreMultiplier: 6.0 },
    ],
    createdAt: now - 86400000 * 8,
    updatedAt: now - 86400000 * 2,
  },
]

export const mockTextResources: TextResource[] = [
  { id: 'txt_001', key: 'ui.start_game', category: 'ui', language: 'zh-CN', content: '开始游戏', description: '主菜单开始按钮', variables: [], version: 1, enabled: true, author: 'translator01', createdAt: now - 86400000 * 30, updatedAt: now - 86400000 * 30 },
  { id: 'txt_002', key: 'ui.start_game', category: 'ui', language: 'en-US', content: 'Start Game', description: '主菜单开始按钮', variables: [], version: 1, enabled: true, author: 'translator01', createdAt: now - 86400000 * 30, updatedAt: now - 86400000 * 30 },
  { id: 'txt_003', key: 'ui.start_game', category: 'ui', language: 'ja-JP', content: 'ゲーム開始', description: '主菜单开始按钮', variables: [], version: 1, enabled: true, author: 'translator02', createdAt: now - 86400000 * 25, updatedAt: now - 86400000 * 25 },
  { id: 'txt_004', key: 'level_intro.classic_lv1', category: 'level_intro', language: 'zh-CN', content: '欢迎来到钟楼。将时钟从 {from} 调整到 {to}，容差 {tolerance} 分钟。', description: '经典第一关开场介绍', variables: ['from', 'to', 'tolerance'], version: 2, enabled: true, author: 'writer01', createdAt: now - 86400000 * 20, updatedAt: now - 86400000 * 5 },
  { id: 'txt_005', key: 'level_intro.classic_lv1', category: 'level_intro', language: 'en-US', content: 'Welcome to the Clock Tower. Adjust the clock from {from} to {to} within {tolerance} minutes tolerance.', description: '经典第一关开场介绍', variables: ['from', 'to', 'tolerance'], version: 1, enabled: true, author: 'translator01', createdAt: now - 86400000 * 18, updatedAt: now - 86400000 * 18 },
  { id: 'txt_006', key: 'tutorial.gear_basic', category: 'tutorial', language: 'zh-CN', content: '点击齿轮可以旋转它。齿轮之间相互连接，会带动其他齿轮转动。', description: '齿轮基础操作教程', variables: [], version: 1, enabled: true, author: 'writer01', createdAt: now - 86400000 * 22, updatedAt: now - 86400000 * 22 },
  { id: 'txt_007', key: 'tutorial.gear_basic', category: 'tutorial', language: 'en-US', content: 'Click on a gear to rotate it. Gears are interconnected and will drive other gears.', description: '齿轮基础操作教程', variables: [], version: 1, enabled: true, author: 'translator01', createdAt: now - 86400000 * 20, updatedAt: now - 86400000 * 20 },
  { id: 'txt_008', key: 'story.prologue', category: 'story', language: 'zh-CN', content: '百年钟楼，岁月流转。你是新任的守钟人，肩负着守护时间流转的重任……', description: '故事序章', variables: [], version: 3, enabled: true, author: 'writer01', createdAt: now - 86400000 * 28, updatedAt: now - 86400000 * 2 },
  { id: 'txt_009', key: 'tooltip.gear_jam', category: 'tooltip', language: 'zh-CN', content: '齿轮卡住了！快速连续点击可以解除故障。', description: '齿轮卡顿提示', variables: [], version: 1, enabled: true, author: 'writer01', createdAt: now - 86400000 * 15, updatedAt: now - 86400000 * 15 },
  { id: 'txt_010', key: 'achievement.first_clear', category: 'achievement', language: 'zh-CN', content: '首次通关！你成功守护了时间的流转。', description: '首次通关成就描述', variables: [], version: 1, enabled: true, author: 'writer01', createdAt: now - 86400000 * 12, updatedAt: now - 86400000 * 12 },
  { id: 'txt_011', key: 'error.level_load_failed', category: 'error', language: 'zh-CN', content: '关卡加载失败：{message}', description: '关卡加载错误提示', variables: ['message'], version: 1, enabled: true, author: 'admin', createdAt: now - 86400000 * 10, updatedAt: now - 86400000 * 10 },
  { id: 'txt_012', key: 'ui.settings', category: 'ui', language: 'zh-CN', content: '设置', description: '设置按钮', variables: [], version: 1, enabled: true, author: 'translator01', createdAt: now - 86400000 * 25, updatedAt: now - 86400000 * 25 },
]

export const mockVersions: ConfigVersion[] = [
  {
    id: 'ver_001',
    version: 'v1.0.0',
    name: '正式首发版',
    description: '游戏正式上线的第一个版本，包含基础关卡和核心玩法',
    status: 'archived',
    levelIds: ['level_001', 'level_002'],
    eventTemplateIds: ['evt_tpl_001', 'evt_tpl_002'],
    difficultyCurveIds: ['diff_easy', 'diff_normal'],
    textResourceIds: ['txt_001', 'txt_002', 'txt_004', 'txt_005', 'txt_006', 'txt_007', 'txt_008', 'txt_009', 'txt_010', 'txt_011', 'txt_012'],
    changeLog: '1. 基础游戏框架完成\n2. 经典模式 2 个关卡\n3. 基础音效系统\n4. 多国语言支持（中/英）',
    publishedAt: now - 86400000 * 30,
    archivedAt: now - 86400000 * 15,
    createdAt: now - 86400000 * 35,
    author: 'admin',
  },
  {
    id: 'ver_002',
    version: 'v1.1.0',
    name: '夜巡模式更新',
    description: '新增夜巡模式，包含 4 个时段的循环关卡',
    status: 'published',
    levelIds: ['level_001', 'level_002', 'level_003'],
    eventTemplateIds: ['evt_tpl_001', 'evt_tpl_002', 'evt_tpl_005'],
    difficultyCurveIds: ['diff_easy', 'diff_normal', 'diff_hard'],
    textResourceIds: ['txt_001', 'txt_002', 'txt_003', 'txt_004', 'txt_005', 'txt_006', 'txt_007', 'txt_008', 'txt_009', 'txt_010', 'txt_011', 'txt_012'],
    changeLog: '1. 新增夜巡游戏模式\n2. 新增 1 个夜巡关卡\n3. 新增高难度曲线\n4. 添加日语翻译\n5. 优化音效系统',
    publishedAt: now - 86400000 * 5,
    createdAt: now - 86400000 * 15,
    author: 'admin',
  },
  {
    id: 'ver_003',
    version: 'v1.2.0-beta',
    name: '风暴机制测试版',
    description: '测试风暴闪电机制，包含新的高难度关卡',
    status: 'draft',
    levelIds: ['level_001', 'level_002', 'level_003', 'level_004'],
    eventTemplateIds: ['evt_tpl_001', 'evt_tpl_002', 'evt_tpl_003', 'evt_tpl_005'],
    difficultyCurveIds: ['diff_easy', 'diff_normal', 'diff_hard', 'diff_expert'],
    textResourceIds: ['txt_001', 'txt_002', 'txt_003', 'txt_004', 'txt_005', 'txt_006', 'txt_007', 'txt_008', 'txt_009', 'txt_010', 'txt_011', 'txt_012'],
    changeLog: '1. 新增风暴闪电机制\n2. 新增风暴关卡\n3. 新增大师难度曲线\n4. 优化故障事件系统',
    createdAt: now - 86400000 * 3,
    author: 'designer01',
  },
  {
    id: 'ver_004',
    version: 'v1.0.1-hotfix',
    name: 'v1.0.0 紧急回滚',
    description: '由于 v1.1.0 出现严重 Bug，回滚至 v1.0.0 稳定版',
    status: 'rolled_back',
    levelIds: ['level_001', 'level_002'],
    eventTemplateIds: ['evt_tpl_001', 'evt_tpl_002'],
    difficultyCurveIds: ['diff_easy', 'diff_normal'],
    textResourceIds: ['txt_001', 'txt_002', 'txt_004', 'txt_005', 'txt_006', 'txt_007', 'txt_008', 'txt_009', 'txt_010', 'txt_011', 'txt_012'],
    changeLog: '回滚至 v1.0.0 稳定版本，临时修复严重崩溃问题',
    rolledBackFrom: 'ver_002',
    createdAt: now - 86400000 * 12,
    author: 'admin',
  },
]

export const mockDashboardStats: DashboardStats = {
  totalLevels: 4,
  publishedLevels: 2,
  totalEvents: 5,
  totalTexts: 12,
  activeVersions: 1,
  lastPublishedAt: now - 86400000 * 5,
  quickStats: [
    { label: '活跃关卡', value: 2, trend: 'up', trendValue: '+1' },
    { label: '本周编辑次数', value: 23, trend: 'up', trendValue: '+40%' },
    { label: '文案翻译进度', value: '92%', trend: 'up', trendValue: '+5%' },
    { label: '待审核项', value: 3, trend: 'flat', trendValue: '0' },
  ],
}
