import type {
  TourHotspot,
  TourMechanismPath,
  TourAudioTrack,
  TourHistoricalFact,
} from '../../types/tour'

export const TOUR_HOTSPOTS: TourHotspot[] = [
  {
    id: 'hotspot_main_gear',
    name: '主传动齿轮',
    displayName: '主传动齿轮',
    category: 'gear',
    icon: '⚙️',
    x: 0.5,
    y: 0.5,
    radius: 0.12,
    order: 1,
    description: '钟楼的心脏，直径达两米的黄铜主齿轮。每一次转动都在为整座钟楼提供动力。',
    historicalNote: '铸造于1887年，由当时著名的钟表匠师塞缪尔·哈金斯亲自监造。齿轮上的每一道齿痕都经过手工打磨，误差不超过千分之一毫米。',
    mechanicalDetail: '齿数：120齿，材质：95%铜+5%锡合金，转速：每小时转动15度，与分针齿轮的传动比为1:12。',
    audioNarrationId: 'audio_main_gear',
    rewardScore: 100,
    connectedHotspotIds: ['hotspot_hour_gear_left', 'hotspot_hour_gear_right'],
  },
  {
    id: 'hotspot_hour_gear_left',
    name: '左侧时针齿轮',
    displayName: '左侧时针齿轮组',
    category: 'gear',
    icon: '🔩',
    x: 0.25,
    y: 0.35,
    radius: 0.09,
    order: 2,
    description: '连接主齿轮与左上小齿轮的中间传动齿轮组，控制时针的宏观运动。',
    historicalNote: '这组齿轮在1923年经历过一次大修，据说当时的工匠在齿轮轴中藏了一封给未来守钟人的信。',
    mechanicalDetail: '齿数：60齿，与主齿轮传动比2:1，每转动一圈代表时间流逝2小时。',
    audioNarrationId: 'audio_hour_gears',
    rewardScore: 80,
    connectedHotspotIds: ['hotspot_main_gear', 'hotspot_minute_gear_left'],
  },
  {
    id: 'hotspot_hour_gear_right',
    name: '右侧时针齿轮',
    displayName: '右侧时针齿轮组',
    category: 'gear',
    icon: '🔩',
    x: 0.75,
    y: 0.35,
    radius: 0.09,
    order: 3,
    description: '右侧的时针传动齿轮，与左侧齿轮形成对称结构，共同驱动时针的精确运转。',
    historicalNote: '据说七十年前的那个雨夜，就是这组齿轮发出了异常的摩擦声，引起了小雷的注意...',
    mechanicalDetail: '齿数：60齿，与左侧齿轮完全对称，确保传动平衡。',
    audioNarrationId: 'audio_hour_gears',
    rewardScore: 80,
    connectedHotspotIds: ['hotspot_main_gear', 'hotspot_minute_gear_right'],
  },
  {
    id: 'hotspot_minute_gear_left',
    name: '左下分针齿轮',
    displayName: '左下分针齿轮',
    category: 'gear',
    icon: '⚙',
    x: 0.2,
    y: 0.7,
    radius: 0.07,
    order: 4,
    description: '最精密的分针小齿轮，每一个微小的转动都会让分针向前推进一格。',
    historicalNote: '这是整座钟楼中更换最频繁的齿轮。一百多年来，它已经被更换过三次，但每一次都严格按照原始图纸复制。',
    mechanicalDetail: '齿数：40齿，每分钟转动1.5度，是钟楼精度的最终保障。',
    audioNarrationId: 'audio_minute_gears',
    rewardScore: 60,
    connectedHotspotIds: ['hotspot_hour_gear_left'],
  },
  {
    id: 'hotspot_minute_gear_right',
    name: '右下方分针齿轮',
    displayName: '右下方分针齿轮',
    category: 'gear',
    icon: '⚙',
    x: 0.8,
    y: 0.7,
    radius: 0.07,
    order: 5,
    description: '与左下齿轮对称的分针齿轮，共同承担着精确到每一分钟的职责。',
    historicalNote: '七十年前，小雷就是在这齿轮旁发现了那个奇怪的符号，从此走上了不归路...',
    mechanicalDetail: '齿数：40齿，与左下齿轮同步运转，保证分针两端受力均衡。',
    audioNarrationId: 'audio_minute_gears',
    rewardScore: 60,
    connectedHotspotIds: ['hotspot_hour_gear_right'],
  },
  {
    id: 'hotspot_clock_center',
    name: '钟面核心',
    displayName: '钟面核心·时间之心',
    category: 'historical',
    icon: '🕐',
    x: 0.5,
    y: 0.5,
    radius: 0.15,
    order: 6,
    description: '钟楼的钟面，所有齿轮的运转最终都汇聚于此——指针的每一次移动，都是时间的心跳。',
    historicalNote: '钟面采用了19世纪罕见的"蓝金珐琅"工艺，数字由纯金镶嵌，历经百年依然熠熠生辉。据说在月圆之夜，钟面会泛出淡淡的蓝光...',
    mechanicalDetail: '钟面直径：5.2米，时针长：2.1米，分针长：2.8米，指针材质：碳化钨钢。',
    audioNarrationId: 'audio_clock_face',
    rewardScore: 150,
    connectedHotspotIds: ['hotspot_main_gear', 'hotspot_twelve_marker'],
  },
  {
    id: 'hotspot_twelve_marker',
    name: '十二点刻度',
    displayName: '十二点·正中之位',
    category: 'historical',
    icon: '✨',
    x: 0.5,
    y: 0.15,
    radius: 0.06,
    order: 7,
    description: '钟面最高点的十二点刻度，是新旧一天交替的见证者。',
    historicalNote: '这个刻度下方藏着一个只有初代守钟人才知道的秘密——一个小小的铜制隔层，里面放着钟楼的奠基徽章。',
    mechanicalDetail: '采用三重嵌套工艺：外层黄金、中层红铜、内层白金，象征日月星三光同辉。',
    audioNarrationId: 'audio_twelve_marker',
    rewardScore: 120,
    connectedHotspotIds: ['hotspot_clock_center', 'hotspot_secret_vault'],
  },
  {
    id: 'hotspot_pendulum_chamber',
    name: '钟摆室入口',
    displayName: '钟摆室·看不见的心跳',
    category: 'mechanism',
    icon: '🔔',
    x: 0.5,
    y: 0.88,
    radius: 0.08,
    order: 8,
    description: '通往下方钟摆室的入口，那里悬挂着重达三吨的精密钟摆，是钟楼走时精准的终极保障。',
    historicalNote: '钟摆是伽利略原理的完美应用，据说初代守钟人奥古斯塔夫人的嫁妆——一颗大钻石，就镶嵌在钟摆的底部。',
    mechanicalDetail: '钟摆长度：3.2米，摆动周期：2秒，温度补偿装置：因瓦合金杆，日误差：±0.5秒。',
    audioNarrationId: 'audio_pendulum',
    rewardScore: 200,
    connectedHotspotIds: ['hotspot_main_gear'],
  },
  {
    id: 'hotspot_bell_rope',
    name: '敲钟绳',
    displayName: '仪式敲钟绳',
    category: 'mechanism',
    icon: '🔕',
    x: 0.08,
    y: 0.5,
    radius: 0.06,
    order: 9,
    description: '通往钟楼顶的粗大麻绳，只有在特殊时刻才会被拉动，让百年铜钟发出响彻云霄的轰鸣。',
    historicalNote: '这根绳子在1956年8月47日——不，应该是8月17日——那天晚上，曾被人用力拉过三次，然后...一切都改变了。',
    mechanicalDetail: '麻绳直径：4厘米，内含钢丝绳芯，可承受最大拉力：5吨。',
    audioNarrationId: 'audio_bell_rope',
    rewardScore: 180,
    connectedHotspotIds: ['hotspot_secret_vault'],
  },
  {
    id: 'hotspot_keeper_desk',
    name: '守钟人工作台',
    displayName: '守钟人的工作台',
    category: 'historical',
    icon: '📖',
    x: 0.92,
    y: 0.5,
    radius: 0.07,
    order: 10,
    description: '历代守钟人记录观察日志的地方，桌面上还留着上一任守钟人艾德温的老花镜。',
    historicalNote: '工作台抽屉里保存着自1887年以来每一位守钟人的日志，共计47本。其中一本的最后一页，写着"我会把他带回来"。',
    mechanicalDetail: '桌面有暗格机关，需要将铜制镇纸旋转特定角度才能开启。',
    audioNarrationId: 'audio_keeper_desk',
    rewardScore: 150,
    connectedHotspotIds: ['hotspot_gear_oil'],
  },
  {
    id: 'hotspot_gear_oil',
    name: '润滑油罐',
    displayName: '百年润滑油罐',
    category: 'mechanism',
    icon: '🛢️',
    x: 0.88,
    y: 0.75,
    radius: 0.05,
    order: 11,
    description: '一只铜制的老式油壶，里面装着专供钟楼齿轮使用的特制润滑油。',
    historicalNote: '润滑油的配方是守钟人世代相传的秘密，据说其中混合了喜马拉雅雪松精油、琥珀粉，还有一点点...时间的味道。',
    mechanicalDetail: '基础油：矿物油+合成酯，添加剂：纳米铜颗粒、抗氧剂、极压剂。使用周期：每半年一次。',
    audioNarrationId: 'audio_gear_oil',
    rewardScore: 90,
    connectedHotspotIds: ['hotspot_keeper_desk'],
  },
  {
    id: 'hotspot_weather_vane',
    name: '风向标连接轴',
    displayName: '风向与时间',
    category: 'mechanism',
    icon: '🌬️',
    x: 0.12,
    y: 0.22,
    radius: 0.05,
    order: 12,
    description: '连接钟楼顶部风向标与内部显示机构的精巧传动装置，让守钟人在室内就能知道外面的风向。',
    historicalNote: '据说在那个风雨交加的夜晚，风向标疯狂旋转，指向了一个从未在气象记录中出现过的方向——西北偏北。',
    mechanicalDetail: '传动比：72:1，风向标每旋转一圈，室内指针旋转5度。采用磁流体密封，确保百年不卡滞。',
    audioNarrationId: 'audio_weather_vane',
    rewardScore: 110,
  },
  {
    id: 'hotspot_secret_vault',
    name: '隐秘隔层',
    displayName: '时间密室的入口',
    category: 'secret',
    icon: '🔮',
    x: 0.5,
    y: 0.12,
    radius: 0.05,
    order: 13,
    isSecret: true,
    description: '（只有当你足够接近时才能感受到）十二点刻度后方，似乎有一个不属于这个时代的空间...',
    historicalNote: '时间密室——只有当钟面上所有指针同时指向十二点，并且校时精度达到零误差时才会开启的禁忌之门。七十年前，小雷就是从这里进入了时间的缝隙。',
    mechanicalDetail: '触发条件：1) 当前时间=目标时间=12:00；2) 连续三次完美校时；3) 访问过所有其他热点。',
    audioNarrationId: 'audio_secret_vault',
    unlockCondition: {
      type: 'all_visited',
      hotspotIds: [],
    },
    rewardScore: 500,
    connectedHotspotIds: ['hotspot_twelve_marker', 'hotspot_bell_rope'],
  },
  {
    id: 'hotspot_rose_window',
    name: '玫瑰窗花',
    displayName: '永恒玫瑰·彩色玻璃窗',
    category: 'historical',
    icon: '🌹',
    x: 0.15,
    y: 0.15,
    radius: 0.07,
    order: 14,
    description: '北面墙上镶嵌的巨型彩色玫瑰窗，阳光透过时会在地面投下斑斓的光影。',
    historicalNote: '奥古斯塔夫人生前最爱的地方。据说她去世后，每当夕阳西下，玫瑰花窗中心那片深红色的玻璃会泛出泪光般的光泽。',
    mechanicalDetail: '直径：2.8米，玻璃片数：847片，其中有3片是来自叙利亚的古代"太阳玻璃"。',
    audioNarrationId: 'audio_rose_window',
    rewardScore: 140,
  },
  {
    id: 'hotspot_exit',
    name: '结束参观',
    displayName: '⬅ 结束参观，返回主界面',
    category: 'exit',
    icon: '🚪',
    x: 0.06,
    y: 0.94,
    radius: 0.06,
    order: 99,
    description: '感谢您参观百年钟楼。愿您在时光中，找到属于自己的答案。',
    rewardScore: 0,
  },
]

export const TOUR_MECHANISM_PATHS: TourMechanismPath[] = [
  {
    id: 'path_main_drive',
    name: '主传动路径',
    displayName: '主传动链',
    description: '动力从钟摆室出发，经过主齿轮，最终传递到四根指针的完整路径。',
    color: '#c9a96a',
    glowColor: '#ffd700',
    points: [
      { x: 0.5, y: 0.88 },
      { x: 0.5, y: 0.68 },
      { x: 0.5, y: 0.5 },
      { x: 0.35, y: 0.42 },
      { x: 0.25, y: 0.35 },
      { x: 0.2, y: 0.52 },
      { x: 0.2, y: 0.7 },
    ],
    relatedGearIds: [0, 1, 3],
    flowDirection: 'clockwise',
    energyTransferRate: 98.5,
    historicalContext: '这条传动路径自1887年建成以来，除了必要的润滑外从未大修，堪称维多利亚时代工程学的奇迹。',
  },
  {
    id: 'path_right_branch',
    name: '右侧传动分支',
    displayName: '右侧传动分支',
    description: '主齿轮向右侧分出的动力路径，驱动右侧的时针齿轮和分针齿轮。',
    color: '#8b7355',
    glowColor: '#d4af37',
    points: [
      { x: 0.5, y: 0.5 },
      { x: 0.65, y: 0.42 },
      { x: 0.75, y: 0.35 },
      { x: 0.8, y: 0.52 },
      { x: 0.8, y: 0.7 },
    ],
    relatedGearIds: [0, 2, 4],
    flowDirection: 'clockwise',
    energyTransferRate: 98.2,
    historicalContext: '传说在七十年前的那个雨夜，正是这条路径上的齿轮发出了不同寻常的"咔嗒"声...',
  },
  {
    id: 'path_hand_connection',
    name: '指针连接路径',
    displayName: '指针驱动系统',
    description: '将齿轮的旋转运动转化为指针的精确位移的核心连接。',
    color: '#5dade2',
    glowColor: '#85c1e9',
    points: [
      { x: 0.5, y: 0.5 },
      { x: 0.5, y: 0.35 },
      { x: 0.5, y: 0.25 },
      { x: 0.5, y: 0.15 },
    ],
    relatedGearIds: [0],
    flowDirection: 'bidirectional',
    energyTransferRate: 99.8,
    historicalContext: '指针轴是由整块碳化钨钢车削而成，据说能承受5000年的磨损而不松动。',
  },
  {
    id: 'path_secret_flow',
    name: '隐秘能量线',
    displayName: '时间能量线',
    description: '（只有在发现密室后才能看见）从钟面十二点通向时间密室的看不见的能量流动路径。',
    color: '#a569bd',
    glowColor: '#bb8fce',
    points: [
      { x: 0.5, y: 0.5 },
      { x: 0.5, y: 0.35 },
      { x: 0.5, y: 0.22 },
      { x: 0.5, y: 0.12 },
    ],
    relatedGearIds: [0],
    flowDirection: 'counterclockwise',
    energyTransferRate: 100,
    historicalContext: '这不是普通的机械能传递——这是时间本身的流动。七十年前，小雷感受到了它的召唤...',
  },
]

export const TOUR_AUDIO_TRACKS: TourAudioTrack[] = [
  {
    id: 'audio_intro',
    title: '欢迎辞·守钟人的问候',
    narrator: '艾德温·哈金斯',
    durationMs: 45000,
    textContent: '欢迎来到旧钟楼，我是艾德温·哈金斯，在这座塔里工作了一辈子的老守钟人。七十年前，这里发生了一件让所有人都无法释怀的事。但今天，在你成功校准了时间之后，这座沉睡了太久的钟楼，终于愿意向你展示它内心深处的秘密了。请慢慢走，用心看——每一个齿轮，每一道划痕，都在诉说着时间的故事...',
    backgroundFrequencies: [110, 220, 330],
    ambientType: 'gear_hum',
  },
  {
    id: 'audio_main_gear',
    title: '主齿轮·心脏的律动',
    narrator: '艾德温·哈金斯',
    durationMs: 38000,
    textContent: '你眼前的就是钟楼的心脏——主传动齿轮。它于1887年在谢菲尔德铸造，当时用了整整三吨的最好的黄铜。塞缪尔·哈金斯，我的曾祖父，亲自监督了整个铸造过程。你仔细听——每一次转动的声音，都是"滴答"两声，像是在呼吸一样。我曾祖父说过，这个齿轮是有生命的，它的心跳，就是时间的心跳...',
    backgroundFrequencies: [82.4, 164.8],
    ambientType: 'gear_hum',
  },
  {
    id: 'audio_hour_gears',
    title: '时针齿轮·时间的呼吸',
    narrator: '滴答（钟表精灵）',
    durationMs: 32000,
    textContent: '叮铃～你找到小时齿轮啦！我最喜欢看它们转动了，慢悠悠的，像老爷爷在散步一样。你知道吗？1923年的工匠爷爷在左齿轮里藏了一封信哦！他说"给一百年后那个会听懂齿轮说话的孩子"——哇，那不就是你嘛！信上写了什么？我也不知道呢，因为我从来没打开过呀～嘻嘻！',
    backgroundFrequencies: [130.8, 261.6],
    ambientType: 'bell_echo',
  },
  {
    id: 'audio_minute_gears',
    title: '分针齿轮·光阴的脚步',
    narrator: '艾德温·哈金斯',
    durationMs: 30000,
    textContent: '分针齿轮是整座钟楼最勤劳的工人。它们从未停歇，一分一秒，一齿一齿地推动着时间向前。七十年前的那天晚上，小雷就是在右下方的这个齿轮旁边蹲了很久很久。他后来说，他听到了齿轮在"哭泣"。当时我以为是孩子的幻觉，现在...我宁愿相信那是真的。',
    backgroundFrequencies: [196, 392],
    ambientType: 'gear_hum',
  },
  {
    id: 'audio_clock_face',
    title: '钟面·时间的容颜',
    narrator: '奥古斯塔（幽灵守护者）',
    durationMs: 52000,
    textContent: '（一个温柔而苍老的女声）...陌生人，你听见了吗？这座钟面，是我丈夫留给我的最后的礼物。1887年的那个夏天，他说"亲爱的，我要为你造一面全世界最美的钟面，让你每一次看时间，都是在看一幅画"。蓝金珐琅的工艺，早已失传了。塞缪尔说，他把我们的爱情，烧进了每一摄氏度的窑火里。七十年了，亲爱的...我还在等你回来...',
    backgroundFrequencies: [65.4, 130.8, 261.6],
    ambientType: 'bell_echo',
  },
  {
    id: 'audio_twelve_marker',
    title: '十二点·原点',
    narrator: '滴答（钟表精灵）',
    durationMs: 28000,
    textContent: '十二点是最神奇的时间哦！因为在那一瞬间，所有的指针都重叠在一起——过去、现在、未来，变成了同一个点！小雷以前最喜欢十二点了，他说如果在十二点整闭上眼睛，许一个愿望，时间老人就会听到。呵呵，不知道他最后许的愿望，实现了没有呢...',
    backgroundFrequencies: [523.25, 659.25, 783.99],
    ambientType: 'bell_echo',
  },
  {
    id: 'audio_pendulum',
    title: '钟摆·永恒的节拍器',
    narrator: '艾德温·哈金斯',
    durationMs: 40000,
    textContent: '钟摆是伽利略在比萨大教堂里发现的原理——不管摆动幅度大小，周期都是一样的。我们这台钟摆，重三吨，长度三米二，每两秒精确地摆动一次。一天八万六千四百秒，它整整工作了一百三十七年，一秒都不差。奥古斯塔夫人的钻石就在钟摆底部——有人说，是钻石的能量让钟摆永远不会停。我更愿意相信，是他们的爱情，在驱动着时间本身。',
    backgroundFrequencies: [440, 880],
    ambientType: 'bell_echo',
  },
  {
    id: 'audio_bell_rope',
    title: '敲钟绳·最后的钟声',
    narrator: '艾德温·哈金斯',
    durationMs: 48000,
    textContent: '（声音颤抖）这根绳子...那天晚上，我比小雷晚到了十分钟。当我推开门时，只看到它还在晃动——三下，不多不少，仪式的序曲。然后...然后钟楼顶传来了一道蓝光，等我冲上去的时候，什么都没有了。只有铜钟还在嗡嗡地响着，像是在...呜咽。七十年了，我每晚都在想，如果那天我再早到十分钟，会不会...一切都会不同？',
    backgroundFrequencies: [98, 196, 294],
    ambientType: 'wind',
  },
  {
    id: 'audio_keeper_desk',
    title: '守钟人日志·四十六代传承',
    narrator: '系统旁白',
    durationMs: 35000,
    textContent: '自1887年以来，共有47位守钟人在这张工作台上记录下了他们的观察。从维多利亚时代的鹅毛笔，到现代的圆珠笔，字迹各不相同，但每页的开头都是同一句话："今日，钟楼一切安好。"但第46本日志，也就是艾德温的上一本，最后一页只有潦草的一行字，墨迹被泪水晕开："对不起，塞缪尔，我没守住你的孙子。"',
    backgroundFrequencies: [220, 330, 440],
    ambientType: 'silent',
  },
  {
    id: 'audio_gear_oil',
    title: '润滑油·流动的时间',
    narrator: '滴答（钟表精灵）',
    durationMs: 25000,
    textContent: '嘿嘿，这个油壶好香哦！有一种松树林里雨后的味道～以前艾德温爷爷给齿轮上油的时候，我都会偷偷飞进去打滚呢！不过有一次我被油粘住了翅膀，困在齿轮之间整整三天！后来还是小雷发现了我，用指尖轻轻把我救出来的...（声音变小）小雷的手指好暖和哦...',
    backgroundFrequencies: [392, 523.25],
    ambientType: 'gear_hum',
  },
  {
    id: 'audio_weather_vane',
    title: '风向标·反常之夜',
    narrator: '艾德温·哈金斯',
    durationMs: 33000,
    textContent: '西北偏北。那天晚上的风向标，指着这个方向整整转了三圈，然后卡死了。气象局第二天说，那天的风向是东风，持续稳定。但我亲眼看见的——西北偏北，那个方向是...墓园。小雷的父母，就葬在那个方向的小山坡上。也许那天晚上，是风把他们的思念，送到了儿子的心里吧。',
    backgroundFrequencies: [146.8, 293.7],
    ambientType: 'wind',
  },
  {
    id: 'audio_secret_vault',
    title: '时间密室·七十年的等待',
    narrator: '小雷的声音',
    durationMs: 62000,
    textContent: '（一个少年的声音，仿佛从很远的地方传来）...你终于来了。我等了好久好久。这里是时间的缝隙，进来的那一刻，我就再也无法回头了。但是我不后悔——我看到了爸爸妈妈最后一面，看到了他们对我笑，告诉我他们爱我。这就够了。守钟人，谢谢你把时间校准。当你听到这段声音的时候，说明我的选择是对的。时间的河流不会倒流，但每一个分支，都值得被记住。再见了，替我告诉艾德温爷爷——我爱他，从未怪过他。替我告诉滴答——继续做一只快乐的精灵吧。还有...替我看看明天的日出，好吗？',
    backgroundFrequencies: [261.6, 392, 523.25, 659.25, 783.99],
    ambientType: 'bell_echo',
  },
  {
    id: 'audio_rose_window',
    title: '玫瑰窗·不朽的爱',
    narrator: '奥古斯塔（幽灵守护者）',
    durationMs: 42000,
    textContent: '（声音中带着微笑）塞缪尔知道我喜欢玫瑰，但他没法让花园里的玫瑰永远开放，所以他造了这扇永不凋零的玫瑰窗。你看到那片最深的红色玻璃了吗？那是我结婚那天礼服的颜色。工匠们说，烧制时加入了我一滴指尖的血，所以它才会红得像心跳一样真实。一百多年了...我依然能感受到他的温度。也许这就是爱真正的样子——哪怕肉体消散，玻璃也会替我们，永远鲜艳。',
    backgroundFrequencies: [329.6, 440, 523.25],
    ambientType: 'silent',
  },
  {
    id: 'audio_ending',
    title: '尾声·黎明',
    narrator: '合声',
    durationMs: 38000,
    textContent: '（艾德温的声音）谢谢你，年轻的守钟人。（奥古斯塔的声音）谢谢你愿意倾听我们的故事。（滴答的声音）嘻嘻！以后你就是我最好的朋友啦！（小雷的声音，轻柔遥远）下次来的时候，记得带一束黑玫瑰，放在十二点的刻度下。（合声）时间会流逝，记忆会褪色，但有些东西——爱、守护、坚持，会像这座钟楼一样，永远矗立在那里，见证每一个黎明的到来。愿你安好，守钟人。',
    backgroundFrequencies: [261.6, 329.6, 392, 523.25, 659.25, 783.99],
    ambientType: 'bell_echo',
  },
]

export const TOUR_HISTORICAL_FACTS: TourHistoricalFact[] = [
  {
    id: 'fact_construction',
    year: 1887,
    era: '维多利亚时代晚期',
    title: '钟楼奠基',
    content:
      '由著名钟表匠师塞缪尔·哈金斯设计并监造，耗资相当于当时一个中产家庭三十年的收入。建造过程中共使用了327吨铜、156吨钢和75万块手工烧制的砖。',
    category: 'architecture',
    source: '《哈金斯家族编年史》，1902年版',
    relatedHotspotIds: ['hotspot_main_gear', 'hotspot_bell_chamber'],
  },
  {
    id: 'fact_inauguration',
    year: 1889,
    era: '维多利亚时代晚期',
    title: '落成典礼',
    content:
      '1889年6月15日正午十二点整，钟楼正式启用。当时全镇万人空巷，只为聆听第一声钟响。据说钟声传到了27公里外的邻镇，创下了当时的记录。',
    category: 'culture',
    source: '《镇志·公共建筑卷》',
    relatedHotspotIds: ['hotspot_clock_center', 'hotspot_bell_tower'],
  },
  {
    id: 'fact_war',
    year: 1940,
    era: '第二次世界大战',
    title: '战火中的守护者',
    content:
      '二战期间，钟楼周围投下了三枚炸弹，附近房屋大多被毁，但钟楼本身只受了轻微擦伤。守钟人哈金斯一家在钟楼地下室度过了整个战争期间，从未让钟声停歇一天。',
    category: 'culture',
    source: '艾德温·哈金斯回忆录片段（1975）',
    relatedHotspotIds: ['hotspot_main_gear', 'hotspot_escapement'],
  },
  {
    id: 'fact_disappearance',
    year: 1956,
    era: '战后重建期',
    title: '小雷的失踪',
    content:
      '8月17日，年仅14岁的守钟学徒小雷在钟楼内神秘失踪。监控显示他从未离开，但大规模搜查一无所获。官方结论是"意外坠楼被钟声掩盖"，但至今无人找到遗骸。',
    category: 'mystery',
    source: '警局档案编号 1956-0817-CK',
    relatedHotspotIds: ['hotspot_secret_vault', 'hotspot_minute_gear_right'],
  },
  {
    id: 'fact_closure',
    year: 1957,
    era: '战后重建期',
    title: '沉默的开始',
    content:
      '小雷失踪后，艾德温·哈金斯拒绝再让钟声响起。这一停，就是七十年。镇民们从抗议到理解，最后接受了这座"沉默的钟楼"。',
    category: 'culture',
    source: '《镇报》1957年3月12日社论',
    relatedHotspotIds: ['hotspot_bell_chamber', 'hotspot_bell_hammer'],
  },
  {
    id: 'fact_museum',
    year: 2003,
    era: '新世纪',
    title: '时间博物馆',
    content:
      '钟楼被改造成"时间博物馆"，对公众开放参观。但最深处的机械室依然不对游客开放——只有通过"校时考验"的人，才有资格一窥究竟。',
    category: 'architecture',
    source: '博物馆官方导览册',
    relatedHotspotIds: ['hotspot_corridor', 'hotspot_main_door'],
  },
  {
    id: 'fact_samuel',
    year: 1842,
    era: '维多利亚时代中期',
    title: '塞缪尔·哈金斯',
    content:
      '钟楼的建造者，出身贫寒的钟表天才。14岁时在伦敦街头修好了一位公爵的怀表，从此改变命运。他的座右铭是"时间是最公平的——它不会因为贫穷而少给一秒，也不会因为富有而多给一分"。',
    category: 'people',
    source: '《时间的匠人——哈金斯传》',
    relatedHotspotIds: ['hotspot_keeper_panel', 'hotspot_clock_center'],
  },
  {
    id: 'fact_augusta',
    year: 1848,
    era: '维多利亚时代中期',
    title: '奥古斯塔·哈金斯',
    content:
      '塞缪尔的妻子，出身贵族家庭。为了嫁给贫穷的钟表匠，她与家族断绝了关系。她将全部嫁妆投入了钟楼的建造，并亲自挑选了每一块彩色玻璃。',
    category: 'people',
    source: '《被遗忘的女性·工业卷》',
    relatedHotspotIds: ['hotspot_clock_center', 'hotspot_main_door'],
  },
  {
    id: 'fact_edwin',
    year: 1932,
    era: '战前',
    title: '艾德温·哈金斯',
    content:
      '塞缪尔的曾孙，最后一任全职守钟人。将小雷视若己出，却在1956年那一夜永远失去了他。此后终生未婚，将全部心血投入了钟楼的维护中。',
    category: 'people',
    source: '艾德温私人日记（2001年由镇史馆公布）',
    relatedHotspotIds: ['hotspot_keeper_panel', 'hotspot_anchor'],
  },
  {
    id: 'fact_xiaolei',
    year: 1942,
    era: '战时',
    title: '小雷',
    content:
      '雷蒙德·陈，中文名陈念祖。父母在1944年的空袭中双亡，被艾德温收养并收为学徒。天赋异禀，能听懂齿轮的"语言"，是公认的下任守钟人人选。',
    category: 'people',
    source: '艾德温私人日记（2001年由镇史馆公布）',
    relatedHotspotIds: ['hotspot_escapement', 'hotspot_secret_vault'],
  },
]

export const TOUR_INITIAL_AUDIO_ID = 'audio_intro'
export const TOUR_ENDING_AUDIO_ID = 'audio_ending'
export const TOUR_SECRET_HOTSPOT_ID = 'hotspot_secret_vault'
