import type {
  MuseumCharacter,
  MuseumScene,
  MuseumChapter,
  MuseumEnding,
  MuseumItem,
  MuseumPuzzleConfig,
  MuseumSceneBackground,
  DialogNode,
} from '../../types/museum'

export const MUSEUM_BACKGROUNDS: MuseumSceneBackground[] = [
  {
    id: 'bg_museum_gate',
    name: '博物馆大门',
    gradient: 'linear-gradient(180deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    description: '一座维多利亚时代风格的钟楼矗立在眼前，铜制大门泛着幽光。',
  },
  {
    id: 'bg_lobby',
    name: '大厅',
    gradient: 'linear-gradient(180deg, #2c1810 0%, #3d2914 50%, #4a3520 100%)',
    description: '高大的穹顶大厅，中央悬挂着华丽的水晶吊灯，四周陈列着古钟表。',
  },
  {
    id: 'bg_clock_hall',
    name: '时钟展厅',
    gradient: 'linear-gradient(180deg, #1e2a1e 0%, #2d3e2a 50%, #3a5038 100%)',
    description: '数百座大小不一的钟表同时运转，齿轮的咔嗒声回荡在展厅中。',
  },
  {
    id: 'bg_gear_room',
    name: '齿轮室',
    gradient: 'linear-gradient(180deg, #2a1a0a 0%, #3a2818 50%, #4a3828 100%)',
    description: '巨大的铜制齿轮互相咬合，缓慢而坚定地转动着。',
  },
  {
    id: 'bg_bell_tower',
    name: '钟楼顶',
    gradient: 'linear-gradient(180deg, #0a1929 0%, #132f4c 50%, #1e4976 100%)',
    description: '星空下的钟楼顶，巨大的铜钟静静悬挂，等待被敲响的那一刻。',
  },
  {
    id: 'bg_library',
    name: '守钟人图书馆',
    gradient: 'linear-gradient(180deg, #1a0a2e 0%, #2a1a4e 50%, #3a2a6e 100%)',
    description: '高耸的书架直抵天花板，尘封的古卷诉说着钟楼的秘密。',
  },
  {
    id: 'bg_time_vault',
    name: '时光密室',
    gradient: 'linear-gradient(180deg, #16213e 0%, #1a1a4e 50%, #2a2a6e 100%)',
    description: '神秘的蓝光从墙壁的裂缝中渗出，空气中弥漫着时间的气息。',
  },
  {
    id: 'bg_rose_garden',
    name: '月夜玫瑰园',
    gradient: 'linear-gradient(180deg, #1a0a1a 0%, #2e1a2e 50%, #422a42 100%)',
    description: '月光洒在盛开的黑玫瑰上，花园中央有一座古老的日晷。',
  },
  {
    id: 'bg_ending_good',
    name: '黎明降临',
    gradient: 'linear-gradient(180deg, #1e3a5f 0%, #4a6fa5 40%, #e8a87c 70%, #f8b195 100%)',
    description: '第一缕晨光穿透云层，钟楼在朝阳中闪耀。',
  },
  {
    id: 'bg_ending_true',
    name: '永恒时光',
    gradient: 'linear-gradient(180deg, #2c003e 0%, #512b58 30%, #fe346e 60%, #ffbd69 100%)',
    description: '时间不再流动，一切都成为了永恒的一部分。',
  },
  {
    id: 'bg_ending_bad',
    name: '无尽黑夜',
    gradient: 'linear-gradient(180deg, #0a0a0a 0%, #1a0a0a 50%, #2a0a0a 100%)',
    description: '钟楼的指针永远停在了午夜，黑暗吞噬了一切。',
  },
  {
    id: 'bg_ending_secret',
    name: '穿越时空',
    gradient: 'linear-gradient(180deg, #00d2ff 0%, #3a7bd5 33%, #6a3093 66%, #a044ff 100%)',
    description: '时空隧道在眼前展开，无数的可能性在闪烁。',
  },
  {
    id: 'bg_ending_bittersweet',
    name: '旧梦重温',
    gradient: 'linear-gradient(180deg, #355C7D 0%, #6C5B7B 50%, #C06C84 100%)',
    description: '有些东西挽回了，但也有些永远失去了。',
  },
  {
    id: 'bg_transition',
    name: '过渡场景',
    gradient: 'linear-gradient(180deg, #0f0f1e 0%, #1a1a2e 100%)',
    description: '场景变换中...',
  },
]

export const MUSEUM_CHARACTERS: MuseumCharacter[] = [
  {
    id: 'narrator',
    name: '旁白',
    displayName: '旁白',
    avatar: '📖',
    color: '#c9a96a',
    description: '讲述故事的神秘声音。',
  },
  {
    id: 'player',
    name: '守钟学徒',
    displayName: '守钟学徒',
    avatar: '🧑‍🎓',
    color: '#5dade2',
    description: '年轻的守钟学徒，被派来调查钟楼的异常。',
  },
  {
    id: 'old_keeper',
    name: '老守钟人',
    displayName: '艾德温·哈金斯',
    avatar: '🧙‍♂️',
    color: '#f5b041',
    description: '在钟楼工作了六十年的老守钟人，知道许多不为人知的秘密。',
  },
  {
    id: 'ghost_guardian',
    name: '幽灵守护者',
    displayName: '奥古斯塔',
    avatar: '👻',
    color: '#a569bd',
    description: '百年前去世的初代守钟人的妻子，她的灵魂一直守护着钟楼。',
  },
  {
    id: 'clock_spirit',
    name: '钟表精灵',
    displayName: '滴答',
    avatar: '✨',
    color: '#58d68d',
    description: '钟楼中诞生的时间精灵，只有心灵纯净的人才能看见。',
  },
  {
    id: 'mysterious_visitor',
    name: '神秘访客',
    displayName: '？？？',
    avatar: '🎭',
    color: '#e74c3c',
    description: '深夜来访的神秘人物，似乎与钟楼的过去有着千丝万缕的联系。',
  },
  {
    id: 'young_apprentice',
    name: '小学徒',
    displayName: '小雷',
    avatar: '👦',
    color: '#f1948a',
    description: '七十年前在钟楼失踪的小学徒，他的下落至今成谜。',
  },
]

export const MUSEUM_ITEMS: MuseumItem[] = [
  {
    id: 'old_key',
    name: '黄铜钥匙',
    displayName: '泛黄的黄铜钥匙',
    icon: '🗝️',
    description: '老守钟人交给你的钥匙，似乎能打开钟楼深处的某扇门。',
    category: 'key',
    usableInPuzzleIds: ['puzzle_gear_room_door'],
  },
  {
    id: 'pocket_watch',
    name: '怀表',
    displayName: '艾德温的怀表',
    icon: '⌚',
    description: '走时精准的老怀表，背面刻着"献给我最爱的学生"。',
    category: 'artifact',
  },
  {
    id: 'time_crystal',
    name: '时间水晶',
    displayName: '破碎的时间水晶',
    icon: '💎',
    description: '散发着淡蓝色光芒的水晶碎片，据说能控制时间的流动。',
    category: 'artifact',
    usableInPuzzleIds: ['puzzle_final_calibration'],
  },
  {
    id: 'diary_page',
    name: '日记残页',
    displayName: '小雷的日记',
    icon: '📜',
    description: '"我发现了齿轮室的秘密...那个符号...如果我能..."',
    category: 'clue',
  },
  {
    id: 'rose_token',
    name: '玫瑰徽章',
    displayName: '黑玫瑰徽章',
    icon: '🌹',
    description: '奥古斯塔的遗物，徽章背面刻着"时光不老，我们不散"。',
    category: 'artifact',
  },
  {
    id: 'bell_hammer',
    name: '敲钟锤',
    displayName: '仪式敲钟锤',
    icon: '🔨',
    description: '历代守钟人使用的敲钟锤，只有心怀敬意之人才能敲响钟声。',
    category: 'tool',
    usableInPuzzleIds: ['puzzle_bell_chime'],
  },
  {
    id: 'star_map',
    name: '星图',
    displayName: '百年前的星图',
    icon: '🗺️',
    description: '标注着某个特殊星座的古老星图，星星的位置似乎在暗示什么。',
    category: 'clue',
    usableInPuzzleIds: ['puzzle_constellation'],
  },
  {
    id: 'music_box',
    name: '音乐盒',
    displayName: '机械音乐盒',
    icon: '🎵',
    description: '奏出一段熟悉旋律的音乐盒，曲调中隐藏着特殊的钟声编码。',
    category: 'clue',
    usableInPuzzleIds: ['puzzle_bell_chord'],
  },
  {
    id: 'lubricant',
    name: '钟表润滑油',
    displayName: '特制润滑油',
    icon: '🛢️',
    description: '能让生锈的齿轮重新运转的珍贵润滑油。',
    category: 'consumable',
    usableInPuzzleIds: ['puzzle_gear_sequence'],
  },
  {
    id: 'magnifier',
    name: '放大镜',
    displayName: '古董放大镜',
    icon: '🔍',
    description: '能看清钟表零件细微之处的放大镜。',
    category: 'tool',
  },
  {
    id: 'letter',
    name: '未寄出的信',
    displayName: '艾德温的信',
    icon: '✉️',
    description: '一封写给小雷家人的信，墨迹因岁月而模糊，但字迹依然工整。',
    category: 'clue',
  },
  {
    id: 'time_essence',
    name: '时光精粹',
    displayName: '凝固的时光',
    icon: '⏳',
    description: '只有在真结局才能获得的神秘物质，据说能改变已发生的事。',
    category: 'artifact',
  },
]

export const MUSEUM_PUZZLES: MuseumPuzzleConfig[] = [
  {
    id: 'puzzle_entry_clock',
    type: 'clock_calibration',
    name: '大厅时钟校准',
    description: '大厅中央的时钟停了，按照老守钟人的指示，将它拨到3:15分。',
    difficulty: 1,
    targetTime: { hours: 3, minutes: 15 },
    toleranceMinutes: 3,
    hint: '时针指向3，分针指向3。',
    rewardScore: 500,
    rewardItemId: 'old_key',
    successSceneId: 'ch1_after_puzzle',
  },
  {
    id: 'puzzle_gear_sequence',
    type: 'gear_sequence',
    name: '齿轮联动',
    description: '三组齿轮必须分别对齐正确的角度：120°、240°、180°。注意齿轮会反向联动！',
    difficulty: 2,
    gearSequence: [120, 240, 180],
    hint: '先从中间的齿轮开始，它会同时影响左右两个。',
    rewardScore: 800,
    rewardItemId: 'lubricant',
    successSceneId: 'ch2_gear_success',
    failSceneId: 'ch2_gear_fail',
  },
  {
    id: 'puzzle_symbol_decipher',
    type: 'symbol_decipher',
    name: '密文破译',
    description: '日记上的符号是密码，按照星图上的顺序：☀️→🌙→⭐→☄️',
    difficulty: 2,
    symbolPattern: ['☀️', '🌙', '⭐', '☄️'],
    hint: '太阳→月亮→星星→彗星。',
    rewardScore: 700,
    rewardItemId: 'star_map',
    successSceneId: 'ch2_symbol_success',
  },
  {
    id: 'puzzle_bell_chord',
    type: 'bell_chord',
    name: '和弦钟声',
    description: '音乐盒的旋律对应 C4、E4、G4、C5 四个音。',
    difficulty: 3,
    bellNotes: ['C4', 'E4', 'G4', 'C5'],
    hint: 'C大调的主三和弦加高八度根音。',
    rewardScore: 1000,
    rewardItemId: 'bell_hammer',
    successSceneId: 'ch3_bell_success',
  },
  {
    id: 'puzzle_constellation',
    type: 'constellation',
    name: '星座连线',
    description: '按照星图上的标注，连接五颗星星组成"守钟者"星座。',
    difficulty: 3,
    constellationPattern: [
      { x: 50, y: 20 },
      { x: 30, y: 45 },
      { x: 70, y: 45 },
      { x: 40, y: 75 },
      { x: 60, y: 75 },
    ],
    hint: '头部→左肩→右肩→左腿→右腿。',
    rewardScore: 900,
    rewardItemId: 'time_crystal',
    successSceneId: 'ch3_star_success',
  },
  {
    id: 'puzzle_time_portal',
    type: 'time_portal',
    name: '时光之门',
    description: '要打开时光之门，需要将时钟调到70年前事故发生的那一刻——晚上8:47。',
    difficulty: 4,
    targetTime: { hours: 8, minutes: 47 },
    toleranceMinutes: 2,
    hint: '时针接近9，分针指向第47分钟的位置。',
    rewardScore: 1200,
    rewardItemId: 'diary_page',
    successSceneId: 'ch4_portal_open',
    failSceneId: 'ch4_portal_fail',
  },
  {
    id: 'puzzle_final_calibration',
    type: 'clock_calibration',
    name: '最终校准',
    description: '钟楼的主钟需要在黎明6:00整被校准，这决定了钟楼的命运。',
    difficulty: 5,
    targetTime: { hours: 6, minutes: 0 },
    toleranceMinutes: 1,
    hint: '时针在6，分针在12。一丝不差。',
    rewardScore: 2000,
    rewardItemId: 'time_essence',
    timeLimitSeconds: 120,
    successSceneId: 'ch5_final_good',
    failSceneId: 'ch5_final_bad',
  },
  {
    id: 'puzzle_bell_chime',
    type: 'bell_chord',
    name: '终章钟鸣',
    description: '按照七十年前的仪式敲响钟声：D4、F4、A4、C5、E5。',
    difficulty: 4,
    bellNotes: ['D4', 'F4', 'A4', 'C5', 'E5'],
    hint: 'D小调五声音阶。',
    rewardScore: 1500,
    successSceneId: 'ch5_bell_true',
  },
]

const prologueDialogs: DialogNode[] = [
  {
    id: 'p_d1',
    speaker: 'narrator',
    text: '1956年，一个风雨交加的夜晚。',
  },
  {
    id: 'p_d2',
    speaker: 'narrator',
    text: '坐落于小镇中央的百年钟楼，发生了一起离奇的事故。',
  },
  {
    id: 'p_d3',
    speaker: 'narrator',
    text: '年仅14岁的守钟学徒小雷，在齿轮室中神秘失踪。',
  },
  {
    id: 'p_d4',
    speaker: 'narrator',
    text: '没有人知道他去了哪里。从那以后，钟楼的钟声就再也没有响起过。',
  },
  {
    id: 'p_d5',
    speaker: 'narrator',
    text: '七十年后——',
  },
  {
    id: 'p_d6',
    speaker: 'narrator',
    text: '钟楼被改造成了一座"时间博物馆"。',
  },
  {
    id: 'p_d7',
    speaker: 'narrator',
    text: '而你，作为守钟人世家的传人，被派来解决最近频繁发生的"时间异常"。',
  },
  {
    id: 'p_d8',
    speaker: 'narrator',
    text: '博物馆的大门在你面前缓缓打开...',
  },
  {
    id: 'p_d9',
    speaker: 'narrator',
    text: '你踏入了这座沉睡了七十年的钟楼。',
  },
]

const ch1EntryDialogs: DialogNode[] = [
  {
    id: 'c1_e1',
    speaker: 'old_keeper',
    text: '你终于来了，孩子。我是艾德温，这座钟楼的最后一任守钟人。',
    emotion: 'neutral',
  },
  {
    id: 'c1_e2',
    speaker: 'player',
    text: '艾德温先生？您看起来...不，您应该已经超过一百岁了。',
    emotion: 'surprised',
  },
  {
    id: 'c1_e3',
    speaker: 'old_keeper',
    text: '（苦笑）时间在这里的流动方式...有些特别。先进来吧，我会告诉你一切。',
    emotion: 'sad',
  },
  {
    id: 'c1_e4',
    speaker: 'narrator',
    text: '大厅中陈列着上百座古钟表，但它们都停在了同一个时刻——8:47。',
  },
  {
    id: 'c1_e5',
    speaker: 'old_keeper',
    text: '看到了吗？所有的钟都停在七十年前出事的那个晚上。',
    emotion: 'sad',
  },
  {
    id: 'c1_e6',
    speaker: 'old_keeper',
    text: '我们必须让时间重新流动起来。孩子，先把大厅中央那座主钟修好。',
    emotion: 'neutral',
  },
  {
    id: 'c1_e7',
    speaker: 'old_keeper',
    text: '它指向的时间应该是3:15。这是我第一次遇见小雷的时间。',
    emotion: 'happy',
  },
  {
    id: 'c1_e8',
    speaker: 'player',
    text: '小雷？那个失踪的学徒？',
    emotion: 'surprised',
  },
  {
    id: 'c1_e9',
    speaker: 'old_keeper',
    text: '（沉默片刻）先修好钟吧，孩子。修好之后，我会告诉你全部的故事。',
    emotion: 'mysterious',
  },
]

const ch1AfterPuzzleDialogs: DialogNode[] = [
  {
    id: 'c1_a1',
    speaker: 'narrator',
    text: '当指针精准对齐3:15的那一刻，大厅中所有的钟表同时开始走动！',
  },
  {
    id: 'c1_a2',
    speaker: 'clock_spirit',
    text: '叮铃～有人来了吗？终于有人能修好钟了！',
    emotion: 'happy',
  },
  {
    id: 'c1_a3',
    speaker: 'player',
    text: '谁...谁在说话？',
    emotion: 'surprised',
  },
  {
    id: 'c1_a4',
    speaker: 'clock_spirit',
    text: '是我是我！滴答～我是这座钟楼的钟表精灵。只有修好钟的人才能看见我哦！',
    emotion: 'happy',
  },
  {
    id: 'c1_a5',
    speaker: 'old_keeper',
    text: '（叹气）滴答，别吓到孩子了。七十年了，你还是这么活泼。',
    emotion: 'happy',
  },
  {
    id: 'c1_a6',
    speaker: 'clock_spirit',
    text: '艾德温爷爷！你终于愿意和我说话了！我以为你还在怪我...',
    emotion: 'sad',
  },
  {
    id: 'c1_a7',
    speaker: 'old_keeper',
    text: '我从来没有怪过你，滴答。那天的事...没有人有错。',
    emotion: 'sad',
  },
  {
    id: 'c1_a8',
    speaker: 'old_keeper',
    text: '孩子，这把钥匙是你的了。它能打开通往齿轮室的门。',
    emotion: 'neutral',
    onEnter: [{ type: 'add_item', key: 'old_key' }],
  },
  {
    id: 'c1_a9',
    speaker: 'old_keeper',
    text: '在齿轮室，你会找到更多关于那天的线索。但是...',
    emotion: 'mysterious',
  },
  {
    id: 'c1_a10',
    speaker: 'player',
    text: '但是？',
    emotion: 'surprised',
  },
  {
    id: 'c1_a11',
    speaker: 'old_keeper',
    text: '做好心理准备。有些真相，一旦揭开就无法回头了。',
    emotion: 'mysterious',
  },
]

const ch1ChoiceDialog: DialogNode = {
  id: 'c1_choice',
  speaker: 'narrator',
  text: '你会如何选择？',
  choices: [
    {
      id: 'ch1_enter_gear',
      text: '🔧 前往齿轮室（开始第二章）',
      nextSceneId: 'ch2_intro',
      effect: { type: 'unlock_chapter', key: 'ch1_complete' },
    },
    {
      id: 'ch1_talk_more',
      text: '💬 先向艾德温了解更多小雷的事',
      nextSceneId: 'ch1_talk_more',
    },
    {
      id: 'ch1_explore_lobby',
      text: '🔍 在大厅四处探索一下',
      nextSceneId: 'ch1_explore',
    },
  ],
}

const ch1TalkMoreDialogs: DialogNode[] = [
  {
    id: 'c1_t1',
    speaker: 'player',
    text: '艾德温先生，您能再多告诉我一些关于小雷的事吗？',
    emotion: 'neutral',
  },
  {
    id: 'c1_t2',
    speaker: 'old_keeper',
    text: '（怀念地）小雷啊...他是我见过最有天赋的孩子。十二岁就来到钟楼，什么齿轮啊钟摆啊，看一遍就会。',
    emotion: 'happy',
  },
  {
    id: 'c1_t3',
    speaker: 'old_keeper',
    text: '他说他要做这个世界上最好的守钟人，让钟楼的钟声传遍世界的每个角落。',
    emotion: 'sad',
  },
  {
    id: 'c1_t4',
    speaker: 'clock_spirit',
    text: '小雷最厉害了！他能听懂齿轮的声音，还能和我说话呢！',
    emotion: 'happy',
  },
  {
    id: 'c1_t5',
    speaker: 'old_keeper',
    text: '是的...那天晚上，他说他发现了钟楼的秘密。一个能让时间"回去"的秘密。',
    emotion: 'mysterious',
  },
  {
    id: 'c1_t6',
    speaker: 'player',
    text: '让时间回去？',
    emotion: 'surprised',
  },
  {
    id: 'c1_t7',
    speaker: 'old_keeper',
    text: '小雷的父母...在他来钟楼的前一年，遭遇意外去世了。',
    emotion: 'sad',
  },
  {
    id: 'c1_t8',
    speaker: 'old_keeper',
    text: '他一直以为，如果能回到过去，就能救回他们。',
    emotion: 'sad',
    onEnter: [{ type: 'add_score', key: '', value: 200 }],
  },
  {
    id: 'c1_t9',
    speaker: 'old_keeper',
    text: '好了，说的够多了。去齿轮室吧，剩下的，你自己去发现。',
    emotion: 'sad',
    nextSceneId: 'ch1_decision',
  },
]

const ch2IntroDialogs: DialogNode[] = [
  {
    id: 'c2_i1',
    speaker: 'narrator',
    text: '你用黄铜钥匙打开了通往齿轮室的门。',
  },
  {
    id: 'c2_i2',
    speaker: 'narrator',
    text: '巨大的铜制齿轮在你眼前缓缓转动，发出沉闷的咔嗒声。',
  },
  {
    id: 'c2_i3',
    speaker: 'clock_spirit',
    text: '哇～好久没来这里了！你看你看，这些齿轮已经生锈好多了呢。',
    emotion: 'sad',
  },
  {
    id: 'c2_i4',
    speaker: 'narrator',
    text: '在齿轮组旁边，你发现了一本泛黄的日记。',
  },
  {
    id: 'c2_i5',
    speaker: 'player',
    text: '（拿起日记）这是...小雷的日记？',
    emotion: 'surprised',
    onEnter: [{ type: 'add_item', key: 'diary_page' }],
  },
  {
    id: 'c2_i6',
    speaker: 'clock_spirit',
    text: '是小雷的！那天晚上他就在这里写日记，写完之后他就...呜呜呜...',
    emotion: 'sad',
  },
  {
    id: 'c2_i7',
    speaker: 'player',
    text: '（翻开日记）"齿轮室深处有一道密码门，密码是四个符号。星图上有答案..."',
    emotion: 'neutral',
  },
  {
    id: 'c2_i8',
    speaker: 'narrator',
    text: '你注意到齿轮室有两个需要解决的问题：',
  },
  {
    id: 'c2_i9',
    speaker: 'narrator',
    text: '第一：三组齿轮需要调整到正确的角度才能让主发条启动。',
  },
  {
    id: 'c2_i10',
    speaker: 'narrator',
    text: '第二：深处的密码门需要破译符号密码才能进入。',
  },
]

const ch2ChoiceDialog: DialogNode = {
  id: 'c2_choice',
  speaker: 'narrator',
  text: '你决定先解决哪个问题？',
  choices: [
    {
      id: 'ch2_do_gear',
      text: '⚙️ 先调整齿轮组',
      nextSceneId: 'ch2_puzzle_gear',
    },
    {
      id: 'ch2_do_symbol',
      text: '🔣 先破译符号密码',
      nextSceneId: 'ch2_puzzle_symbol',
    },
    {
      id: 'ch2_explore',
      text: '🔍 四处走走，看看有没有其他线索',
      nextSceneId: 'ch2_explore',
    },
  ],
}

const ch2GearSuccessDialogs: DialogNode[] = [
  {
    id: 'c2_gs1',
    speaker: 'narrator',
    text: '三组齿轮同时发出清脆的"咔嗒"声，完美对齐！',
  },
  {
    id: 'c2_gs2',
    speaker: 'narrator',
    text: '主发条开始转动，整座钟楼的机械系统复苏了！',
  },
  {
    id: 'c2_gs3',
    speaker: 'clock_spirit',
    text: '太棒啦！齿轮又重新转起来了！谢谢你，守钟人！',
    emotion: 'happy',
    onEnter: [{ type: 'add_score', key: '', value: 300 }],
  },
  {
    id: 'c2_gs4',
    speaker: 'narrator',
    text: '齿轮的转动让墙壁上的一幅画移开了，露出了一张星图！',
  },
  {
    id: 'c2_gs5',
    speaker: 'player',
    text: '（拿到星图）这就是日记里提到的星图！上面标注了四个符号。',
    emotion: 'happy',
    onEnter: [{ type: 'add_item', key: 'star_map' }],
    nextSceneId: 'ch2_after_one',
  },
]

const ch2SymbolSuccessDialogs: DialogNode[] = [
  {
    id: 'c2_ss1',
    speaker: 'narrator',
    text: '四个符号按顺序亮起，密码门发出"嗡"的一声开了！',
  },
  {
    id: 'c2_ss2',
    speaker: 'player',
    text: '（走入门内）这是...守钟人的私室？',
    emotion: 'surprised',
  },
  {
    id: 'c2_ss3',
    speaker: 'narrator',
    text: '私室中有一张小床、一个书架，还有一瓶陈年的钟表润滑油。',
  },
  {
    id: 'c2_ss4',
    speaker: 'clock_spirit',
    text: '这是小雷的房间！他住在这里呢...他总说这里像个小小的城堡。',
    emotion: 'sad',
    onEnter: [{ type: 'add_score', key: '', value: 200 }],
  },
  {
    id: 'c2_ss5',
    speaker: 'player',
    text: '（拿起润滑油）这个应该能用来对付生锈的齿轮。',
    emotion: 'neutral',
    onEnter: [{ type: 'add_item', key: 'lubricant' }],
    nextSceneId: 'ch2_after_one',
  },
]

const ch2AfterOneDialogs: DialogNode[] = [
  {
    id: 'c2_a1',
    speaker: 'narrator',
    text: '你已经完成了一半的任务。',
  },
  {
    id: 'c2_a2',
    speaker: 'ghost_guardian',
    text: '（一个模糊的身影出现）年轻的守钟人...你做得很好。',
    emotion: 'neutral',
  },
  {
    id: 'c2_a3',
    speaker: 'player',
    text: '您是...？',
    emotion: 'surprised',
  },
  {
    id: 'c2_a4',
    speaker: 'ghost_guardian',
    text: '我是奥古斯塔，这座钟楼初代主人的妻子。我的灵魂在此守候了两百年。',
    emotion: 'neutral',
  },
  {
    id: 'c2_a5',
    speaker: 'ghost_guardian',
    text: '我一直在等待...等待一个愿意倾听真相的人。',
    emotion: 'sad',
  },
  {
    id: 'c2_a6',
    speaker: 'clock_spirit',
    text: '奥古斯塔夫人！您终于愿意出来见人了！',
    emotion: 'happy',
    onEnter: [{ type: 'add_relationship', key: 'ghost_guardian', value: 1 }],
  },
]

const ch2Choice2Dialog: DialogNode = {
  id: 'c2_choice2',
  speaker: 'narrator',
  text: '接下来你会怎么做？',
  choices: [
    {
      id: 'ch2_do_gear2',
      text: '⚙️ 调整齿轮组',
      nextSceneId: 'ch2_puzzle_gear',
      condition: { type: 'flag_not_set', key: 'gear_done' },
    },
    {
      id: 'ch2_do_symbol2',
      text: '🔣 破译符号密码',
      nextSceneId: 'ch2_puzzle_symbol',
      condition: { type: 'flag_not_set', key: 'symbol_done' },
    },
    {
      id: 'ch2_talk_ghost',
      text: '👻 和奥古斯塔夫人谈谈',
      nextSceneId: 'ch2_talk_ghost',
    },
    {
      id: 'ch2_go_next',
      text: '➡️ 前往钟楼顶（第三章）',
      nextSceneId: 'ch3_intro',
      effect: { type: 'unlock_chapter', key: 'ch2_complete' },
      condition: { type: 'flag_set', key: 'ch2_both_done' },
    },
  ],
}

const ch3IntroDialogs: DialogNode[] = [
  {
    id: 'c3_i1',
    speaker: 'narrator',
    text: '螺旋楼梯向上延伸，你一步步走向钟楼顶。',
  },
  {
    id: 'c3_i2',
    speaker: 'narrator',
    text: '推开厚重的木门，夜空在眼前展开。',
  },
  {
    id: 'c3_i3',
    speaker: 'narrator',
    text: '巨大的铜钟悬挂在钟楼之巅，表面布满了岁月的痕迹。',
  },
  {
    id: 'c3_i4',
    speaker: 'old_keeper',
    text: '（不知何时出现在你身后）七十年了，它再也没有被敲响过。',
    emotion: 'sad',
  },
  {
    id: 'c3_i5',
    speaker: 'old_keeper',
    text: '那天晚上，小雷就是站在这里，想要敲响仪式的钟声。',
    emotion: 'sad',
  },
  {
    id: 'c3_i6',
    speaker: 'player',
    text: '仪式钟声？',
    emotion: 'surprised',
  },
  {
    id: 'c3_i7',
    speaker: 'old_keeper',
    text: '百年传承的仪式。在特定的时刻，用特定的旋律敲响钟声，就能打开"时间的缝隙"。',
    emotion: 'mysterious',
  },
  {
    id: 'c3_i8',
    speaker: 'old_keeper',
    text: '小雷他...想用这个方法，回到父母去世之前。',
    emotion: 'sad',
  },
]

const ch3ChoiceDialog: DialogNode = {
  id: 'c3_choice',
  speaker: 'narrator',
  text: '钟楼顶有两个谜题等待解决。你先做什么？',
  choices: [
    {
      id: 'ch3_do_bell',
      text: '🔔 研究钟楼上的钟声编码',
      nextSceneId: 'ch3_puzzle_bell',
    },
    {
      id: 'ch3_do_star',
    text: '⭐ 观察夜空中的星座',
      nextSceneId: 'ch3_puzzle_constellation',
    },
    {
      id: 'ch3_talk_edwin',
      text: '💬 向艾德温询问仪式的细节',
      nextSceneId: 'ch3_talk_edwin',
    },
  ],
}

const ch4IntroDialogs: DialogNode[] = [
  {
    id: 'c4_i1',
    speaker: 'narrator',
    text: '齿轮室的最深处，一扇被蓝光笼罩的门静静矗立。',
  },
  {
    id: 'c4_i2',
    speaker: 'ghost_guardian',
    text: '这就是时间之门。小雷就是从这里消失的。',
    emotion: 'sad',
  },
  {
    id: 'c4_i3',
    speaker: 'player',
    text: '如果打开这扇门...我能找到他吗？',
    emotion: 'neutral',
  },
  {
    id: 'c4_i4',
    speaker: 'ghost_guardian',
    text: '也许吧。但你要知道，进入这扇门的人，有可能永远迷失在时间的洪流中。',
    emotion: 'mysterious',
  },
  {
    id: 'c4_i5',
    speaker: 'clock_spirit',
    text: '我我我...我也可以去的！我熟悉时间的味道，我能帮你找到路！',
    emotion: 'happy',
    onEnter: [{ type: 'add_relationship', key: 'clock_spirit', value: 1 }],
  },
]

const ch4ChoiceDialog: DialogNode = {
  id: 'c4_choice',
  speaker: 'narrator',
  text: '站在时间之门前，你的选择是？',
  choices: [
    {
      id: 'ch4_open_portal',
      text: '🚪 打开时间之门，寻找小雷',
      nextSceneId: 'ch4_puzzle_portal',
    },
    {
      id: 'ch4_go_back',
      text: '↩️ 先回到图书馆查找更多资料',
      nextSceneId: 'ch4_library',
    },
    {
      id: 'ch4_talk_ghost_more',
      text: '👻 再向奥古斯塔夫人问问当年的事',
      nextSceneId: 'ch4_talk_ghost',
    },
  ],
}

const ch5FinalChoiceDialog: DialogNode = {
  id: 'c5_choice',
  speaker: 'narrator',
  text: '黎明即将到来。你站在钟楼的主钟前，面前有两条路。',
  choices: [
    {
      id: 'ch5_calibrate',
      text: '⏰ 校准主钟，让时间恢复正常流动',
      nextSceneId: 'ch5_puzzle_final',
      condition: { type: 'score_above', key: '', value: 3000 },
    },
    {
      id: 'ch5_bell_ritual',
      text: '🔔 敲响终章钟鸣，用仪式之力改变过去',
      nextSceneId: 'ch5_puzzle_bell_final',
      requiredItemId: 'bell_hammer',
      condition: { type: 'flag_set', key: 'bell_ritual_unlocked' },
    },
    {
      id: 'ch5_walk_away',
      text: '🚶 放下一切，离开钟楼',
      nextSceneId: 'ending_neutral',
    },
  ],
}

const endingGoodDialogs: DialogNode[] = [
  {
    id: 'e_g1',
    speaker: 'narrator',
    text: '主钟的指针在6:00整完美对齐。',
  },
  {
    id: 'e_g2',
    speaker: 'narrator',
    text: '第一缕阳光穿过云层，照在古老的钟楼上。',
  },
  {
    id: 'e_g3',
    speaker: 'narrator',
    text: '七十年了，钟楼的钟声第一次在黎明时分响起。',
  },
  {
    id: 'e_g4',
    speaker: 'old_keeper',
    text: '（眼含泪光）谢谢你，孩子。小雷...也该安息了。',
    emotion: 'happy',
  },
  {
    id: 'e_g5',
    speaker: 'ghost_guardian',
    text: '七十年的执念，终于可以放下了。艾德温，奥古斯塔也要走了。',
    emotion: 'happy',
  },
  {
    id: 'e_g6',
    speaker: 'narrator',
    text: '幽灵的身影在晨光中渐渐变淡，但她的脸上挂着安详的微笑。',
  },
  {
    id: 'e_g7',
    speaker: 'clock_spirit',
    text: '太好了太好了！以后我就和你一起工作啦！新的守钟人！',
    emotion: 'happy',
  },
  {
    id: 'e_g8',
    speaker: 'narrator',
    text: '时间博物馆重新开放了。',
  },
  {
    id: 'e_g9',
    speaker: 'narrator',
    text: '而你，成为了它的新一任守钟人。',
  },
  {
    id: 'e_g10',
    speaker: 'narrator',
    text: '——好结局·黎明的钟声——',
    onEnter: [{ type: 'add_score', key: '', value: 1000 }],
  },
]

const endingTrueDialogs: DialogNode[] = [
  {
    id: 'e_t1',
    speaker: 'narrator',
    text: '当最后一个音符敲响，整座钟楼被神圣的光芒笼罩。',
  },
  {
    id: 'e_t2',
    speaker: 'narrator',
    text: '你看到了——七十年前那一夜的画面。',
  },
  {
    id: 'e_t3',
    speaker: 'narrator',
    text: '十四岁的小雷站在钟楼顶，面前是打开的时间之门。',
  },
  {
    id: 'e_t4',
    speaker: 'young_apprentice',
    text: '我一定要...我一定要回去救爸爸妈妈...',
    emotion: 'sad',
  },
  {
    id: 'e_t5',
    speaker: 'player',
    text: '小雷，不要去！你回来！',
    emotion: 'surprised',
  },
  {
    id: 'e_t6',
    speaker: 'narrator',
    text: '你伸出手，时间的力量从你的指尖涌出。',
  },
  {
    id: 'e_t7',
    speaker: 'narrator',
    text: '小雷惊讶地看着自己的手——他没有踏入时间之门。',
  },
  {
    id: 'e_t8',
    speaker: 'young_apprentice',
    text: '我...我感觉到了...有人在叫我...守钟人...？',
    emotion: 'surprised',
  },
  {
    id: 'e_t9',
    speaker: 'narrator',
    text: '时间线被重新编织。',
  },
  {
    id: 'e_t10',
    speaker: 'narrator',
    text: '七十年后的现在，一个满头白发的老人推开博物馆的大门。',
  },
  {
    id: 'e_t11',
    speaker: 'mysterious_visitor',
    text: '（微笑）我来了，我终于回家了。谢谢你，守钟人。',
    emotion: 'happy',
  },
  {
    id: 'e_t12',
    speaker: 'narrator',
    text: '小雷没有消失。他活了下来，成为了一位伟大的钟表匠。',
  },
  {
    id: 'e_t13',
    speaker: 'narrator',
    text: '而今天，他终于回到了这个他魂牵梦萦了一辈子的地方。',
  },
  {
    id: 'e_t14',
    speaker: 'narrator',
    text: '——真结局·时光不老——',
    onEnter: [{ type: 'add_score', key: '', value: 3000 }, { type: 'add_item', key: 'time_essence' }],
  },
]

const endingBadDialogs: DialogNode[] = [
  {
    id: 'e_b1',
    speaker: 'narrator',
    text: '主钟的校准失败了。',
  },
  {
    id: 'e_b2',
    speaker: 'narrator',
    text: '指针在午夜12:00的位置疯狂旋转，然后——',
  },
  {
    id: 'e_b3',
    speaker: 'narrator',
    text: '永远地停了下来。',
  },
  {
    id: 'e_b4',
    speaker: 'old_keeper',
    text: '不...不！不能停在午夜！',
    emotion: 'angry',
  },
  {
    id: 'e_b5',
    speaker: 'narrator',
    text: '黑暗从钟楼中涌出，吞噬了一切。',
  },
  {
    id: 'e_b6',
    speaker: 'ghost_guardian',
    text: '不...我们被困住了...永远...',
    emotion: 'sad',
  },
  {
    id: 'e_b7',
    speaker: 'narrator',
    text: '第二天，人们发现钟楼博物馆消失了。',
  },
  {
    id: 'e_b8',
    speaker: 'narrator',
    text: '没有人记得它曾经存在过。',
  },
  {
    id: 'e_b9',
    speaker: 'narrator',
    text: '除了你——在无尽的黑夜中，你依然能听到齿轮的咔嗒声。',
  },
  {
    id: 'e_b10',
    speaker: 'narrator',
    text: '——坏结局·永夜——',
  },
]

const endingNeutralDialogs: DialogNode[] = [
  {
    id: 'e_n1',
    speaker: 'narrator',
    text: '你转身离开了钟楼。',
  },
  {
    id: 'e_n2',
    speaker: 'narrator',
    text: '有些事情，也许永远不该被揭开。',
  },
  {
    id: 'e_n3',
    speaker: 'old_keeper',
    text: '（叹气）也罢...这也是一种选择。',
    emotion: 'sad',
  },
  {
    id: 'e_n4',
    speaker: 'narrator',
    text: '时间博物馆最终还是闭馆了。',
  },
  {
    id: 'e_n5',
    speaker: 'narrator',
    text: '小雷的故事，奥古斯塔的守候，艾德温的执念——',
  },
  {
    id: 'e_n6',
    speaker: 'narrator',
    text: '一切都尘封在了那座再也不会被打开的钟楼里。',
  },
  {
    id: 'e_n7',
    speaker: 'narrator',
    text: '而你，回归了平凡的生活。',
  },
  {
    id: 'e_n8',
    speaker: 'narrator',
    text: '只是偶尔在雨夜，你仿佛还能听到远处传来的钟声...',
  },
  {
    id: 'e_n9',
    speaker: 'narrator',
    text: '——中立结局·尘封的记忆——',
  },
]

const endingBittersweetDialogs: DialogNode[] = [
  {
    id: 'e_bs1',
    speaker: 'narrator',
    text: '你找到了小雷迷失的时间碎片。',
  },
  {
    id: 'e_bs2',
    speaker: 'narrator',
    text: '他的意识还在，但是他的身体已经与时间融为一体，再也回不来了。',
  },
  {
    id: 'e_bs3',
    speaker: 'young_apprentice',
    text: '守钟人...谢谢你找到我。告诉艾德温爷爷，我从来没有怪过他。',
    emotion: 'happy',
  },
  {
    id: 'e_bs4',
    speaker: 'young_apprentice',
    text: '告诉世界...小雷在时间里过得很好。我看到了很多很多美好的事。',
    emotion: 'happy',
  },
  {
    id: 'e_bs5',
    speaker: 'old_keeper',
    text: '（泣不成声）小雷...我的孩子...',
    emotion: 'sad',
  },
  {
    id: 'e_bs6',
    speaker: 'narrator',
    text: '从那以后，钟楼的钟声每天都会响起。',
  },
  {
    id: 'e_bs7',
    speaker: 'narrator',
    text: '听过的人都说，那声音里有一个少年温柔的笑容。',
  },
  {
    id: 'e_bs8',
    speaker: 'narrator',
    text: '有些遗憾无法弥补，但至少，不再有遗憾被遗忘。',
  },
  {
    id: 'e_bs9',
    speaker: 'narrator',
    text: '——苦乐参半结局·钟声里的少年——',
    onEnter: [{ type: 'add_score', key: '', value: 500 }],
  },
]

export const MUSEUM_SCENES: MuseumScene[] = [
  {
    id: 'prologue_intro',
    chapterId: 'prologue',
    type: 'dialog',
    title: '序幕：七十年后的约定',
    backgroundId: 'bg_museum_gate',
    dialogNodes: prologueDialogs,
    autoNextSceneId: 'ch1_entry',
    chapterProgress: 0,
  },
  {
    id: 'ch1_entry',
    chapterId: 'ch1',
    type: 'dialog',
    title: '第一章：醒来的钟楼',
    backgroundId: 'bg_lobby',
    dialogNodes: ch1EntryDialogs,
    autoNextSceneId: 'ch1_puzzle',
    chapterProgress: 10,
  },
  {
    id: 'ch1_puzzle',
    chapterId: 'ch1',
    type: 'puzzle',
    title: '大厅时钟校准',
    backgroundId: 'bg_lobby',
    puzzleId: 'puzzle_entry_clock',
    chapterProgress: 40,
  },
  {
    id: 'ch1_after_puzzle',
    chapterId: 'ch1',
    type: 'dialog',
    title: '第一章：钟表精灵',
    backgroundId: 'bg_lobby',
    dialogNodes: ch1AfterPuzzleDialogs,
    autoNextSceneId: 'ch1_decision',
    onEnterEffects: [{ type: 'set_flag', key: 'ch1_puzzle_done' }],
    chapterProgress: 70,
  },
  {
    id: 'ch1_decision',
    chapterId: 'ch1',
    type: 'dialog',
    title: '第一章：抉择',
    backgroundId: 'bg_lobby',
    dialogNodes: [ch1ChoiceDialog],
    chapterProgress: 85,
  },
  {
    id: 'ch1_talk_more',
    chapterId: 'ch1',
    type: 'dialog',
    title: '第一章：小雷的故事',
    backgroundId: 'bg_lobby',
    dialogNodes: ch1TalkMoreDialogs,
    chapterProgress: 80,
  },
  {
    id: 'ch1_explore',
    chapterId: 'ch1',
    type: 'exploration',
    title: '第一章：大厅探索',
    backgroundId: 'bg_lobby',
    chapterProgress: 80,
    explorationHotspots: [
      {
        id: 'hotspot_lobby_clock',
        name: '落地钟',
        description: '一座精致的落地钟，钟摆下方有一行小字："时间从不等人，但它等爱的人。"',
        x: 15, y: 40, width: 20, height: 45,
        icon: '🕰️',
        oneTime: true,
        effects: [{ type: 'add_score', key: '', value: 50 }],
      },
      {
        id: 'hotspot_lobby_painting',
        name: '油画',
        description: '画中是一个年轻女子和一个男孩站在钟楼前。女子胸前别着一朵黑玫瑰。',
        x: 70, y: 25, width: 20, height: 30,
        icon: '🖼️',
        oneTime: true,
        giveItemId: 'rose_token',
      },
      {
        id: 'hotspot_lobby_desk',
        name: '前台',
        description: '前台放着一只精致的音乐盒。你上紧发条，一段旋律在大厅中回响...',
        x: 40, y: 70, width: 25, height: 20,
        icon: '🎼',
        oneTime: true,
        giveItemId: 'music_box',
      },
      {
        id: 'hotspot_lobby_stairs',
        name: '楼梯',
        description: '通往二楼展厅的楼梯，但现在还不是上去的时候。',
        x: 85, y: 60, width: 10, height: 35,
        icon: '🪜',
        oneTime: false,
      },
      {
        id: 'hotspot_lobby_leave',
        name: '齿轮室入口',
        description: '（你准备好了）',
        x: 5, y: 50, width: 10, height: 30,
        icon: '➡️',
        oneTime: false,
        clickedSceneId: 'ch1_decision',
      },
    ],
  },
  {
    id: 'ch2_intro',
    chapterId: 'ch2',
    type: 'dialog',
    title: '第二章：齿轮与密码',
    backgroundId: 'bg_gear_room',
    dialogNodes: ch2IntroDialogs,
    autoNextSceneId: 'ch2_decision',
    onEnterEffects: [{ type: 'set_flag', key: 'entered_ch2' }],
    chapterProgress: 10,
  },
  {
    id: 'ch2_decision',
    chapterId: 'ch2',
    type: 'dialog',
    title: '第二章：先解决什么？',
    backgroundId: 'bg_gear_room',
    dialogNodes: [ch2ChoiceDialog],
    chapterProgress: 25,
  },
  {
    id: 'ch2_puzzle_gear',
    chapterId: 'ch2',
    type: 'puzzle',
    title: '齿轮联动谜题',
    backgroundId: 'bg_gear_room',
    puzzleId: 'puzzle_gear_sequence',
    chapterProgress: 50,
  },
  {
    id: 'ch2_gear_success',
    chapterId: 'ch2',
    type: 'dialog',
    title: '齿轮启动！',
    backgroundId: 'bg_gear_room',
    dialogNodes: ch2GearSuccessDialogs,
    onEnterEffects: [
      { type: 'set_flag', key: 'gear_done' },
      { type: 'set_flag', key: 'ch2_both_done' },
    ],
    autoNextSceneId: 'ch2_decision2',
    chapterProgress: 65,
  },
  {
    id: 'ch2_gear_fail',
    chapterId: 'ch2',
    type: 'dialog',
    title: '齿轮错位',
    backgroundId: 'bg_gear_room',
    dialogNodes: [
      { id: 'gf1', speaker: 'narrator', text: '齿轮发出刺耳的摩擦声，然后卡住了。' },
      { id: 'gf2', speaker: 'clock_spirit', text: '哎呀！没关系没关系，再试试就好啦！', emotion: 'happy' },
      { id: 'gf3', speaker: 'narrator', text: '你深吸一口气，准备再试一次。', nextSceneId: 'ch2_puzzle_gear' },
    ],
    chapterProgress: 50,
  },
  {
    id: 'ch2_puzzle_symbol',
    chapterId: 'ch2',
    type: 'puzzle',
    title: '符号密码',
    backgroundId: 'bg_gear_room',
    puzzleId: 'puzzle_symbol_decipher',
    chapterProgress: 50,
  },
  {
    id: 'ch2_symbol_success',
    chapterId: 'ch2',
    type: 'dialog',
    title: '密码破译！',
    backgroundId: 'bg_library',
    dialogNodes: ch2SymbolSuccessDialogs,
    onEnterEffects: [
      { type: 'set_flag', key: 'symbol_done' },
      { type: 'set_flag', key: 'ch2_both_done' },
    ],
    autoNextSceneId: 'ch2_decision2',
    chapterProgress: 65,
  },
  {
    id: 'ch2_after_one',
    chapterId: 'ch2',
    type: 'dialog',
    title: '第二章：幽灵现身',
    backgroundId: 'bg_gear_room',
    dialogNodes: ch2AfterOneDialogs,
    autoNextSceneId: 'ch2_decision2',
    chapterProgress: 70,
  },
  {
    id: 'ch2_decision2',
    chapterId: 'ch2',
    type: 'dialog',
    title: '第二章：继续',
    backgroundId: 'bg_gear_room',
    dialogNodes: [ch2Choice2Dialog],
    chapterProgress: 85,
  },
  {
    id: 'ch2_talk_ghost',
    chapterId: 'ch2',
    type: 'dialog',
    title: '第二章：奥古斯塔的故事',
    backgroundId: 'bg_gear_room',
    dialogNodes: [
      { id: 'tg1', speaker: 'ghost_guardian', text: '你想知道小雷失踪那天，到底发生了什么？', emotion: 'sad' },
      { id: 'tg2', speaker: 'player', text: '嗯，如果您愿意告诉我的话。', emotion: 'neutral' },
      { id: 'tg3', speaker: 'ghost_guardian', text: '那天晚上，小雷打开了时间之门。但是...他没有找到他要找的东西。', emotion: 'sad' },
      { id: 'tg4', speaker: 'ghost_guardian', text: '相反，他打开了不该打开的东西。一个来自未来的...回声。', emotion: 'mysterious' },
      { id: 'tg5', speaker: 'player', text: '回声？', emotion: 'surprised' },
      { id: 'tg6', speaker: 'ghost_guardian', text: '一个来自七十年后的你。你现在所做的一切，在那天晚上就已经被小雷看到了。', emotion: 'mysterious' },
      { id: 'tg7', speaker: 'ghost_guardian', text: '这就是他知道自己会成功的原因。因为他看到了你——来救他的人。', emotion: 'happy', onEnter: [{ type: 'add_score', key: '', value: 300 }, { type: 'add_relationship', key: 'ghost_guardian', value: 2 }] },
      { id: 'tg8', speaker: 'narrator', text: '（你感到一阵寒意，似乎有什么深刻的东西在你脑海中闪过。）', nextSceneId: 'ch2_decision2' },
    ],
    chapterProgress: 80,
  },
  {
    id: 'ch2_explore',
    chapterId: 'ch2',
    type: 'exploration',
    title: '第二章：齿轮室探索',
    backgroundId: 'bg_gear_room',
    chapterProgress: 30,
    explorationHotspots: [
      {
        id: 'hotspot_gear_window',
        name: '小窗',
        description: '透过沾满油污的小窗，你看到了月光下的玫瑰园。',
        x: 5, y: 15, width: 15, height: 20,
        icon: '🪟',
        oneTime: true,
        effects: [{ type: 'add_score', key: '', value: 50 }],
      },
      {
        id: 'hotspot_gear_oil',
        name: '工具箱',
        description: '工具箱中有一瓶陈年的钟表润滑油。',
        x: 80, y: 65, width: 15, height: 20,
        icon: '🧰',
        oneTime: true,
        giveItemId: 'lubricant',
        condition: { type: 'no_item', key: 'lubricant' },
      },
      {
        id: 'hotspot_gear_return',
        name: '返回',
        description: '（回到任务选择）',
        x: 45, y: 85, width: 10, height: 10,
        icon: '↩️',
        clickedSceneId: 'ch2_decision',
      },
    ],
  },
  {
    id: 'ch3_intro',
    chapterId: 'ch3',
    type: 'dialog',
    title: '第三章：钟楼顶的秘密',
    backgroundId: 'bg_bell_tower',
    dialogNodes: ch3IntroDialogs,
    autoNextSceneId: 'ch3_decision',
    onEnterEffects: [{ type: 'set_flag', key: 'entered_ch3' }],
    chapterProgress: 10,
  },
  {
    id: 'ch3_decision',
    chapterId: 'ch3',
    type: 'dialog',
    title: '第三章：选择',
    backgroundId: 'bg_bell_tower',
    dialogNodes: [ch3ChoiceDialog],
    chapterProgress: 30,
  },
  {
    id: 'ch3_puzzle_bell',
    chapterId: 'ch3',
    type: 'puzzle',
    title: '钟声和弦',
    backgroundId: 'bg_bell_tower',
    puzzleId: 'puzzle_bell_chord',
    chapterProgress: 55,
  },
  {
    id: 'ch3_bell_success',
    chapterId: 'ch3',
    type: 'dialog',
    title: '钟声响起！',
    backgroundId: 'bg_bell_tower',
    dialogNodes: [
      { id: 'c3b1', speaker: 'narrator', text: '和谐的钟声回荡在夜空，连星星都仿佛在聆听。' },
      { id: 'c3b2', speaker: 'old_keeper', text: '这是...仪式的序章。你成功了！', emotion: 'happy' },
      { id: 'c3b3', speaker: 'narrator', text: '艾德温从怀中取出一把仪式敲钟锤，交到你手中。', onEnter: [{ type: 'add_item', key: 'bell_hammer' }, { type: 'add_score', key: '', value: 500 }] },
      { id: 'c3b4', speaker: 'old_keeper', text: '这是敲终章钟鸣需要的东西。你拿着吧。', emotion: 'neutral', nextSceneId: 'ch3_after' },
    ],
    onEnterEffects: [{ type: 'set_flag', key: 'bell_done' }, { type: 'set_flag', key: 'bell_ritual_unlocked' }],
    chapterProgress: 70,
  },
  {
    id: 'ch3_puzzle_constellation',
    chapterId: 'ch3',
    type: 'puzzle',
    title: '守钟者星座',
    backgroundId: 'bg_bell_tower',
    puzzleId: 'puzzle_constellation',
    chapterProgress: 55,
  },
  {
    id: 'ch3_star_success',
    chapterId: 'ch3',
    type: 'dialog',
    title: '星座发光！',
    backgroundId: 'bg_bell_tower',
    dialogNodes: [
      { id: 'c3s1', speaker: 'narrator', text: '五颗星星被连成一线，夜空中浮现出"守钟者"的轮廓！' },
      { id: 'c3s2', speaker: 'clock_spirit', text: '哇哦！守钟者大人出现了！好厉害！', emotion: 'happy' },
      { id: 'c3s3', speaker: 'narrator', text: '一块散发着淡蓝色光芒的水晶碎片从空中飘落。', onEnter: [{ type: 'add_item', key: 'time_crystal' }, { type: 'add_score', key: '', value: 400 }] },
      { id: 'c3s4', speaker: 'player', text: '（接住水晶）这是...时间水晶？', emotion: 'surprised' },
      { id: 'c3s5', speaker: 'ghost_guardian', text: '时间水晶...小雷当年就是想用这个打开时间之门。', emotion: 'sad', nextSceneId: 'ch3_after' },
    ],
    onEnterEffects: [{ type: 'set_flag', key: 'star_done' }, { type: 'set_flag', key: 'ch3_both_done' }],
    autoNextSceneId: 'ch3_after',
    chapterProgress: 70,
  },
  {
    id: 'ch3_talk_edwin',
    chapterId: 'ch3',
    type: 'dialog',
    title: '第三章：艾德温的秘密',
    backgroundId: 'bg_bell_tower',
    dialogNodes: [
      { id: 'c3te1', speaker: 'player', text: '艾德温先生，能告诉我仪式的完整流程吗？', emotion: 'neutral' },
      { id: 'c3te2', speaker: 'old_keeper', text: '（沉默良久）仪式需要两步。第一步：奏响序章和弦，唤醒钟楼的共鸣。' },
      { id: 'c3te3', speaker: 'old_keeper', text: '第二步：连接"守钟者"星座，获得时间水晶。' },
      { id: 'c3te4', speaker: 'old_keeper', text: '只有同时完成这两步，才能获得敲响终章钟鸣的资格。' },
      { id: 'c3te5', speaker: 'player', text: '那小雷当年...？', emotion: 'surprised' },
      { id: 'c3te6', speaker: 'old_keeper', text: '他太急了。只完成了一半就强行开启了时间之门。' },
      { id: 'c3te7', speaker: 'old_keeper', text: '（声音颤抖）我本可以阻止他的...但我那时...', emotion: 'sad' },
      { id: 'c3te8', speaker: 'clock_spirit', text: '不是的！艾德温爷爷那天是为了救我才...', emotion: 'sad', onEnter: [{ type: 'add_score', key: '', value: 250 }, { type: 'add_relationship', key: 'old_keeper', value: 2 }] },
      { id: 'c3te9', speaker: 'old_keeper', text: '够了，滴答。都过去了。', emotion: 'sad', nextSceneId: 'ch3_decision' },
    ],
    chapterProgress: 50,
  },
  {
    id: 'ch3_after',
    chapterId: 'ch3',
    type: 'dialog',
    title: '第三章：尾声',
    backgroundId: 'bg_bell_tower',
    dialogNodes: [
      {
        id: 'c3a1',
        speaker: 'narrator',
        text: '第三章的任务已经完成。接下来...',
      },
      {
        id: 'c3a2',
        speaker: 'narrator',
        text: '你会如何选择？',
        choices: [
          {
            id: 'c3a_do_bell',
            text: '🔔 研究钟声编码',
            nextSceneId: 'ch3_puzzle_bell',
            condition: { type: 'flag_not_set', key: 'bell_done' },
          },
          {
            id: 'c3a_do_star',
            text: '⭐ 连接星座',
            nextSceneId: 'ch3_puzzle_constellation',
            condition: { type: 'flag_not_set', key: 'star_done' },
          },
          {
            id: 'c3a_go_next',
            text: '➡️ 前往时间之门（第四章）',
            nextSceneId: 'ch4_intro',
            effect: { type: 'unlock_chapter', key: 'ch3_complete' },
            condition: { type: 'flag_set', key: 'ch3_both_done' },
          },
        ],
      },
    ],
    chapterProgress: 85,
  },
  {
    id: 'ch4_intro',
    chapterId: 'ch4',
    type: 'dialog',
    title: '第四章：时间之门',
    backgroundId: 'bg_time_vault',
    dialogNodes: ch4IntroDialogs,
    autoNextSceneId: 'ch4_decision',
    onEnterEffects: [{ type: 'set_flag', key: 'entered_ch4' }],
    chapterProgress: 10,
  },
  {
    id: 'ch4_decision',
    chapterId: 'ch4',
    type: 'dialog',
    title: '第四章：抉择',
    backgroundId: 'bg_time_vault',
    dialogNodes: [ch4ChoiceDialog],
    chapterProgress: 30,
  },
  {
    id: 'ch4_puzzle_portal',
    chapterId: 'ch4',
    type: 'puzzle',
    title: '打开时光之门',
    backgroundId: 'bg_time_vault',
    puzzleId: 'puzzle_time_portal',
    chapterProgress: 60,
  },
  {
    id: 'ch4_portal_open',
    chapterId: 'ch4',
    type: 'dialog',
    title: '门开了...',
    backgroundId: 'bg_time_vault',
    dialogNodes: [
      { id: 'c4po1', speaker: 'narrator', text: '时针指向8:47，时间之门发出耀眼的蓝光！' },
      { id: 'c4po2', speaker: 'ghost_guardian', text: '门开了...小雷的气息...我感觉到了！', emotion: 'happy' },
      { id: 'c4po3', speaker: 'clock_spirit', text: '我们走吧！去把小雷带回来！', emotion: 'happy' },
      { id: 'c4po4', speaker: 'narrator', text: '你和滴答一起，踏入了时间之门。' },
      { id: 'c4po5', speaker: 'narrator', text: '在无数的时间碎片中，你看到了——小雷的身影。', nextSceneId: 'ch4_portal_inside' },
    ],
    onEnterEffects: [{ type: 'set_flag', key: 'portal_opened' }],
    chapterProgress: 80,
  },
  {
    id: 'ch4_portal_fail',
    chapterId: 'ch4',
    type: 'dialog',
    title: '失败',
    backgroundId: 'bg_time_vault',
    dialogNodes: [
      { id: 'c4pf1', speaker: 'narrator', text: '时间剧烈震动，门关上了。' },
      { id: 'c4pf2', speaker: 'ghost_guardian', text: '没关系...再试一次就好。', emotion: 'sad' },
      { id: 'c4pf3', speaker: 'narrator', text: '你深吸一口气，准备再试。', nextSceneId: 'ch4_puzzle_portal' },
    ],
    chapterProgress: 60,
  },
  {
    id: 'ch4_portal_inside',
    chapterId: 'ch4',
    type: 'exploration',
    title: '第四章：时间碎片',
    backgroundId: 'bg_ending_secret',
    chapterProgress: 85,
    explorationHotspots: [
      {
        id: 'hotspot_time_shard1',
        name: '时间碎片1',
        description: '碎片中是小雷12岁时第一次走进钟楼的画面。',
        x: 15, y: 25, width: 18, height: 22,
        icon: '💫',
        oneTime: true,
        effects: [{ type: 'add_score', key: '', value: 150 }],
      },
      {
        id: 'hotspot_time_shard2',
        name: '时间碎片2',
        description: '小雷和艾德温在修钟，两人都笑得很开心。',
        x: 42, y: 40, width: 18, height: 22,
        icon: '💫',
        oneTime: true,
        effects: [{ type: 'add_score', key: '', value: 150 }],
      },
      {
        id: 'hotspot_time_shard3',
        name: '时间碎片3',
        description: '雨夜，小雷独自站在钟楼顶，手中紧握着什么。',
        x: 68, y: 25, width: 18, height: 22,
        icon: '💫',
        oneTime: true,
        effects: [{ type: 'add_score', key: '', value: 150 }],
      },
      {
        id: 'hotspot_lei',
        name: '小雷',
        description: '你找到了迷失在时间洪流中的小雷。',
        x: 42, y: 70, width: 18, height: 22,
        icon: '👦',
        oneTime: true,
        effects: [{ type: 'set_flag', key: 'found_lei' }, { type: 'add_score', key: '', value: 500 }],
        clickedSceneId: 'ch4_lei_found',
      },
    ],
  },
  {
    id: 'ch4_lei_found',
    chapterId: 'ch4',
    type: 'dialog',
    title: '第四章：找到小雷',
    backgroundId: 'bg_ending_secret',
    dialogNodes: [
      { id: 'c4lf1', speaker: 'young_apprentice', text: '你是...？你能看到我？', emotion: 'surprised' },
      { id: 'c4lf2', speaker: 'player', text: '小雷，跟我回去。大家都在等你。', emotion: 'neutral' },
      { id: 'c4lf3', speaker: 'young_apprentice', text: '回去...？我...我还能回去吗？', emotion: 'sad' },
      { id: 'c4lf4', speaker: 'clock_spirit', text: '可以的！滴答带你走！我们回家！', emotion: 'happy' },
      {
        id: 'c4lf5',
        speaker: 'narrator',
        text: '你拉起小雷的手，准备回到现实。',
        choices: [
          {
            id: 'c4lf_go_good',
            text: '🏃 带小雷回到现实（好结局）',
            nextSceneId: 'ch5_decision',
            effect: { type: 'set_flag', key: 'lei_saved' },
          },
          {
            id: 'c4lf_go_bittersweet',
            text: '💔 小雷选择留在时间中（苦乐参半结局）',
            nextSceneId: 'ending_bittersweet',
            condition: { type: 'flag_set', key: 'lei_choice' },
          },
          {
            id: 'c4lf_ask',
            text: '💬 先问问小雷自己的想法',
            nextSceneId: 'ch4_lei_choice',
          },
        ],
      },
    ],
    onEnterEffects: [{ type: 'set_flag', key: 'lei_found' }, { type: 'unlock_chapter', key: 'ch4_complete' }],
    chapterProgress: 95,
  },
  {
    id: 'ch4_lei_choice',
    chapterId: 'ch4',
    type: 'dialog',
    title: '第四章：小雷的选择',
    backgroundId: 'bg_ending_secret',
    dialogNodes: [
      { id: 'c4lc1', speaker: 'player', text: '小雷，你想回去吗？', emotion: 'neutral' },
      { id: 'c4lc2', speaker: 'young_apprentice', text: '我...我想回去。但是...我在这里看到了很多很多。' },
      { id: 'c4lc3', speaker: 'young_apprentice', text: '时间是那么的美...每一秒都是一个故事。' },
      { id: 'c4lc4', speaker: 'young_apprentice', text: '而且，如果我回去了，艾德温爷爷...他还会是现在的他吗？' },
      { id: 'c4lc5', speaker: 'narrator', text: '小雷抬起头，眼中闪烁着复杂的光芒。', onEnter: [{ type: 'set_flag', key: 'lei_choice' }], nextSceneId: 'ch4_lei_found' },
    ],
    chapterProgress: 95,
  },
  {
    id: 'ch4_library',
    chapterId: 'ch4',
    type: 'exploration',
    title: '第四章：图书馆',
    backgroundId: 'bg_library',
    chapterProgress: 40,
    explorationHotspots: [
      {
        id: 'hotspot_lib_oldbook',
        name: '古老笔记',
        description: '笔记上写着："校准主钟于黎明6:00，可让时间恢复流动。"',
        x: 10, y: 30, width: 22, height: 30,
        icon: '📖',
        oneTime: true,
        effects: [{ type: 'set_flag', key: 'know_final_time' }, { type: 'add_score', key: '', value: 200 }],
      },
      {
        id: 'hotspot_lib_ritual',
        name: '仪式手册',
        description: '"终章钟鸣"的仪式曲谱。D F A C E ——这是改变过去的旋律。',
        x: 65, y: 30, width: 22, height: 30,
        icon: '📒',
        oneTime: true,
        effects: [{ type: 'set_flag', key: 'know_ritual' }, { type: 'add_score', key: '', value: 200 }],
      },
      {
        id: 'hotspot_lib_letter',
        name: '未寄出的信',
        description: '艾德温写给小雷家人的信，但他始终没有勇气寄出。',
        x: 40, y: 70, width: 22, height: 22,
        icon: '✉️',
        oneTime: true,
        giveItemId: 'letter',
      },
      {
        id: 'hotspot_lib_return',
        name: '返回',
        description: '（回到时间之门）',
        x: 45, y: 10, width: 10, height: 10,
        icon: '↩️',
        clickedSceneId: 'ch4_decision',
      },
    ],
  },
  {
    id: 'ch4_talk_ghost',
    chapterId: 'ch4',
    type: 'dialog',
    title: '第四章：奥古斯塔的真相',
    backgroundId: 'bg_time_vault',
    dialogNodes: [
      { id: 'c4tg1', speaker: 'ghost_guardian', text: '小雷的事...真的不怪任何人。' },
      { id: 'c4tg2', speaker: 'ghost_guardian', text: '两百年前，我也是因为思念逝去的丈夫，才让灵魂留在了这里。' },
      { id: 'c4tg3', speaker: 'ghost_guardian', text: '我懂那种想回到过去的心情。所以...我没有阻止小雷。' },
      { id: 'c4tg4', speaker: 'ghost_guardian', text: '年轻的守钟人，你愿意原谅我吗？', emotion: 'sad' },
      {
        id: 'c4tg5',
        speaker: 'narrator',
        text: '你会如何回答？',
        choices: [
          {
            id: 'c4tg_forgive',
            text: '💚 原谅奥古斯塔',
            nextSceneId: 'ch4_decision',
            effect: { type: 'add_relationship', key: 'ghost_guardian', value: 3 },
            onEnter: [{ type: 'add_score', key: '', value: 300 }],
          },
          {
            id: 'c4tg_strict',
            text: '💛 理解但不认同',
            nextSceneId: 'ch4_decision',
            effect: { type: 'add_relationship', key: 'ghost_guardian', value: 1 },
          },
        ],
      },
    ],
    chapterProgress: 50,
  },
  {
    id: 'ch5_decision',
    chapterId: 'ch5',
    type: 'dialog',
    title: '终章：黎明将至',
    backgroundId: 'bg_clock_hall',
    dialogNodes: [
      { id: 'c5d1', speaker: 'narrator', text: '你们从时间之门回来了。小雷紧紧握着你的手。' },
      { id: 'c5d2', speaker: 'old_keeper', text: '（泪眼朦胧）小雷...你...你回来了！', emotion: 'happy' },
      { id: 'c5d3', speaker: 'young_apprentice', text: '艾德温爷爷...对不起，让你等了七十年。', emotion: 'sad' },
      { id: 'c5d4', speaker: 'narrator', text: '远方的天际泛起鱼肚白——黎明即将到来。' },
      ch5FinalChoiceDialog,
    ],
    onEnterEffects: [{ type: 'set_flag', key: 'entered_ch5' }],
    chapterProgress: 50,
  },
  {
    id: 'ch5_puzzle_final',
    chapterId: 'ch5',
    type: 'puzzle',
    title: '终章：最终校准',
    backgroundId: 'bg_ending_good',
    puzzleId: 'puzzle_final_calibration',
    chapterProgress: 80,
  },
  {
    id: 'ch5_final_good',
    chapterId: 'ch5',
    type: 'ending',
    title: '结局：黎明的钟声',
    backgroundId: 'bg_ending_good',
    endingId: 'ending_good',
    dialogNodes: endingGoodDialogs,
    onEnterEffects: [{ type: 'unlock_chapter', key: 'ch5_complete' }],
    chapterProgress: 100,
  },
  {
    id: 'ch5_final_bad',
    chapterId: 'ch5',
    type: 'ending',
    title: '结局：永夜',
    backgroundId: 'bg_ending_bad',
    endingId: 'ending_bad',
    dialogNodes: endingBadDialogs,
    chapterProgress: 100,
  },
  {
    id: 'ch5_puzzle_bell_final',
    chapterId: 'ch5',
    type: 'puzzle',
    title: '终章：终章钟鸣',
    backgroundId: 'bg_ending_true',
    puzzleId: 'puzzle_bell_chime',
    chapterProgress: 80,
  },
  {
    id: 'ch5_bell_true',
    chapterId: 'ch5',
    type: 'ending',
    title: '结局：时光不老',
    backgroundId: 'bg_ending_true',
    endingId: 'ending_true',
    dialogNodes: endingTrueDialogs,
    onEnterEffects: [{ type: 'unlock_chapter', key: 'ch5_complete' }],
    chapterProgress: 100,
  },
  {
    id: 'ending_neutral',
    chapterId: 'ch5',
    type: 'ending',
    title: '结局：尘封的记忆',
    backgroundId: 'bg_lobby',
    endingId: 'ending_neutral',
    dialogNodes: endingNeutralDialogs,
    chapterProgress: 100,
  },
  {
    id: 'ending_bittersweet',
    chapterId: 'ch4',
    type: 'ending',
    title: '结局：钟声里的少年',
    backgroundId: 'bg_ending_bittersweet',
    endingId: 'ending_bittersweet',
    dialogNodes: endingBittersweetDialogs,
    chapterProgress: 100,
  },
]

export const MUSEUM_CHAPTERS: MuseumChapter[] = [
  {
    id: 'prologue',
    order: 0,
    title: '序幕',
    subtitle: '七十年后的约定',
    description: '你是守钟人世家的传人，被派往"时间博物馆"解决神秘的时间异常。',
    coverGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    estimatedMinutes: 5,
    sceneIds: ['prologue_intro'],
    prologueSceneId: 'prologue_intro',
    tagline: '欢迎来到沉睡的钟楼',
  },
  {
    id: 'ch1',
    order: 1,
    title: '第一章',
    subtitle: '醒来的钟楼',
    description: '遇到了神秘的老守钟人艾德温和钟表精灵滴答，开始了解钟楼的过去。',
    coverGradient: 'linear-gradient(135deg, #2c1810 0%, #4a3520 100%)',
    estimatedMinutes: 15,
    sceneIds: ['ch1_entry', 'ch1_puzzle', 'ch1_after_puzzle', 'ch1_decision', 'ch1_talk_more', 'ch1_explore'],
    prologueSceneId: 'ch1_entry',
    unlockCondition: { type: 'flag_set', key: 'ch1_complete' },
    tagline: '让时间重新流动',
  },
  {
    id: 'ch2',
    order: 2,
    title: '第二章',
    subtitle: '齿轮与密码',
    description: '深入齿轮室，发现七十年前小雷失踪的线索，遇到了幽灵守护者奥古斯塔。',
    coverGradient: 'linear-gradient(135deg, #2a1a0a 0%, #4a3828 100%)',
    estimatedMinutes: 20,
    sceneIds: ['ch2_intro', 'ch2_decision', 'ch2_puzzle_gear', 'ch2_gear_success', 'ch2_gear_fail', 'ch2_puzzle_symbol', 'ch2_symbol_success', 'ch2_after_one', 'ch2_decision2', 'ch2_talk_ghost', 'ch2_explore'],
    prologueSceneId: 'ch2_intro',
    unlockCondition: { type: 'flag_set', key: 'ch2_complete' },
    tagline: '转动命运的齿轮',
  },
  {
    id: 'ch3',
    order: 3,
    title: '第三章',
    subtitle: '钟楼顶的秘密',
    description: '登上钟楼顶，研究钟声仪式和守钟者星座，艾德温的秘密逐渐浮出水面。',
    coverGradient: 'linear-gradient(135deg, #0a1929 0%, #1e4976 100%)',
    estimatedMinutes: 20,
    sceneIds: ['ch3_intro', 'ch3_decision', 'ch3_puzzle_bell', 'ch3_bell_success', 'ch3_puzzle_constellation', 'ch3_star_success', 'ch3_talk_edwin', 'ch3_after'],
    prologueSceneId: 'ch3_intro',
    unlockCondition: { type: 'flag_set', key: 'ch3_complete' },
    tagline: '倾听星与钟的私语',
  },
  {
    id: 'ch4',
    order: 4,
    title: '第四章',
    subtitle: '时间之门',
    description: '打开传说中的时间之门，在时间碎片中寻找失踪了七十年的小雷。',
    coverGradient: 'linear-gradient(135deg, #16213e 0%, #2a2a6e 100%)',
    estimatedMinutes: 25,
    sceneIds: ['ch4_intro', 'ch4_decision', 'ch4_puzzle_portal', 'ch4_portal_open', 'ch4_portal_fail', 'ch4_portal_inside', 'ch4_lei_found', 'ch4_lei_choice', 'ch4_library', 'ch4_talk_ghost'],
    prologueSceneId: 'ch4_intro',
    unlockCondition: { type: 'flag_set', key: 'ch4_complete' },
    tagline: '跨越七十年的思念',
  },
  {
    id: 'ch5',
    order: 5,
    title: '终章',
    subtitle: '黎明将至',
    description: '黎明即将到来，你将做出最终的选择——钟楼的命运将由你决定。',
    coverGradient: 'linear-gradient(135deg, #1e3a5f 0%, #e8a87c 100%)',
    estimatedMinutes: 15,
    sceneIds: ['ch5_decision', 'ch5_puzzle_final', 'ch5_final_good', 'ch5_final_bad', 'ch5_puzzle_bell_final', 'ch5_bell_true', 'ending_neutral'],
    prologueSceneId: 'ch5_decision',
    unlockCondition: { type: 'flag_set', key: 'ch5_complete' },
    tagline: '做出你的选择',
  },
]

export const MUSEUM_ENDINGS: MuseumEnding[] = [
  {
    id: 'ending_good',
    type: 'good_ending',
    title: '黎明的钟声',
    subtitle: '好结局',
    epilogue: [
      '你校准了主钟，让时间恢复了正常的流动。',
      '小雷虽然没有回来，但他的灵魂终于得以安息。',
      '奥古斯塔放下了两百年的执念，与艾德温告别。',
      '你成为了新一任守钟人，钟楼的钟声每天都在黎明时分准时响起。',
      '一切都结束了，但新的故事，才刚刚开始。',
    ],
    scoreRequirement: 0,
    flagRequirements: ['lei_found'],
    unlockHint: '成功校准主钟即可解锁',
    isCanon: true,
    artGradient: 'linear-gradient(180deg, #1e3a5f 0%, #4a6fa5 40%, #e8a87c 70%, #f8b195 100%)',
  },
  {
    id: 'ending_true',
    type: 'true_ending',
    title: '时光不老',
    subtitle: '真结局',
    epilogue: [
      '你敲响了终章钟鸣，用仪式的力量改写了历史。',
      '小雷没有踏入时间之门，他活了下来。',
      '七十年后，一个满头白发的老人推开了博物馆的大门。',
      '"我回来了。"他说，眼中是跨越了七十年的思念与感激。',
      '时光不老，我们不散。',
    ],
    scoreRequirement: 5000,
    flagRequirements: ['bell_ritual_unlocked', 'lei_found', 'bell_done', 'star_done'],
    itemRequirements: ['bell_hammer', 'time_crystal'],
    unlockHint: '完成所有收集，获得仪式敲钟锤和时间水晶',
    isCanon: true,
    artGradient: 'linear-gradient(180deg, #2c003e 0%, #512b58 30%, #fe346e 60%, #ffbd69 100%)',
  },
  {
    id: 'ending_bad',
    type: 'bad_ending',
    title: '永夜',
    subtitle: '坏结局',
    epilogue: [
      '主钟的校准失败了，指针停在了午夜12:00。',
      '黑暗从钟楼中涌出，吞噬了一切。',
      '第二天，人们发现钟楼博物馆消失了，没有人记得它曾经存在过。',
      '只有你——在无尽的黑夜中，依然能听到齿轮的咔嗒声。',
      '那是永恒的，孤独的回响。',
    ],
    unlockHint: '在最终校准中失败即可解锁',
    artGradient: 'linear-gradient(180deg, #0a0a0a 0%, #1a0a0a 50%, #2a0a0a 100%)',
  },
  {
    id: 'ending_neutral',
    type: 'neutral_ending',
    title: '尘封的记忆',
    subtitle: '中立结局',
    epilogue: [
      '你选择了离开，放下了这一切。',
      '有些事情，也许永远不该被揭开。',
      '钟楼博物馆最终闭馆，小雷的故事尘封在历史中。',
      '而你，回归了平凡的生活。',
      '只是偶尔在雨夜，你仿佛还能听到远处传来的钟声...',
    ],
    unlockHint: '在最终选择离开钟楼即可解锁',
    artGradient: 'linear-gradient(180deg, #2c1810 0%, #4a3520 50%, #6a5540 100%)',
  },
  {
    id: 'ending_bittersweet',
    type: 'bittersweet_ending',
    title: '钟声里的少年',
    subtitle: '苦乐参半结局',
    epilogue: [
      '你找到了小雷，但他选择留在时间之中。',
      '"我看到了太多美好的瞬间，我想把它们都收藏起来。"',
      '从那以后，钟楼的钟声每天都会准时响起。',
      '听过的人都说，那声音里有一个少年温柔的笑容。',
      '有些遗憾无法弥补，但至少，不再有遗憾被遗忘。',
    ],
    scoreRequirement: 2000,
    flagRequirements: ['lei_found', 'lei_choice'],
    unlockHint: '找到小雷后询问他的真实想法',
    artGradient: 'linear-gradient(180deg, #355C7D 0%, #6C5B7B 50%, #C06C84 100%)',
  },
  {
    id: 'ending_secret',
    type: 'secret_ending',
    title: '穿越时空',
    subtitle: '隐藏结局',
    epilogue: [
      '你在时间之门中发现了一个从未被记载的秘密通道。',
      '沿着通道前行，你来到了一个你从未想象过的地方。',
      '无数个平行的钟楼在你眼前展开，每一个都有不同的故事。',
      '"你愿意成为所有钟楼的守钟人吗？"一个声音问你。',
      '你微笑着，点了点头。',
      '——to be continued in Clock Tower Multiverse',
    ],
    scoreRequirement: 8000,
    flagRequirements: ['lei_found', 'bell_done', 'star_done', 'portal_opened', 'know_final_time', 'know_ritual'],
    itemRequirements: ['time_essence', 'rose_token', 'letter', 'music_box'],
    relationshipRequirements: { ghost_guardian: 5, old_keeper: 3, clock_spirit: 3 },
    unlockHint: '收集全部物品，提升所有角色好感度',
    artGradient: 'linear-gradient(180deg, #00d2ff 0%, #3a7bd5 33%, #6a3093 66%, #a044ff 100%)',
  },
]
